### ISSUE TITLE
Do you have an expectation of when https://github.com/pallets/flask-sqlalchemy/pull/613 will be released?

### ISSUE THREAD

**Issue by idavidmcdonald** [pallets/flask-sqlalchemy#1021]
Hi,

Firstly thanks for all your time and maintenance on this!

Secondly, we are currently using a pinned version by commit of Flask-Sqlalchemy so we can get the functionality of https://github.com/pallets/flask-sqlalchemy/pull/613. We'd love to swap back to using an official release as we are missing out on all the other changes and bug fixes.

It was merged in to main about 3.5 years ago. Do you know if this is something likely to be released soon as part of a 2.x release? Just checking in case it had got missed or whether this is still on your radar?

Is there anything that we might be able to do to help get this released?

Once again, thank you :)

**Comment by davidism** [comment]
Sorry, we do not make statements about when a release will be made, as it is not generally possible for the volunteers to predict or guarantee it. Flask-SQLAlchemy needs more maintainers, so if you're willing to dedicate time to learn how to do that and can commit to doing it long term (1 year or more regular attention), then I'm happy to help you start, ping me on https://discord.gg/pallets.
