### ISSUE TITLE
Provide Integration with OpenTelemetry's SQLAlchemy Instrumentor

### ISSUE THREAD

**Issue by proffalken** [pallets/flask-sqlalchemy#1023]
More and more companies are switching to [OpenTelemetry](https://opentelemetry.io/) as a way of providing application tracing and replacing Jaeger/Zipkin.

There is already [an existing Instrumentor for SQLAlchemy](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/sqlalchemy/sqlalchemy.html) as part of the OpenTelemetry Project, it would be great to get that functionality rolled into Flask SqlAlchemy as well!

The current implementation works as follows:

```python
from sqlalchemy import create_engine

from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
import sqlalchemy

engine = create_engine("sqlite:///:memory:")
SQLAlchemyInstrumentor().instrument(
    engine=engine,
)
```
I'm not sure how that would translate to a call to Flask-SqlAlchemy given that the engine is instantiated within the call to `SQLAlchemy(app)`

**Comment by davidism** [comment]
Seems you would call `SQLAlchemyInstrumentor().instrument(db.engine)`. I don't plan to add any particular integration with this to the extension.

**Comment by proffalken** [comment]
OK, thanks @davidism, so just to confirm, the code would be something like this?

```python
db = SQLAlchemy(app)
SQLAlchemyInstrumentor().instrument(db.engine)
```

I'll give that a go, thanks!

**Comment by proffalken** [comment]
Hmmm, what am I missing here?

```bash
Traceback (most recent call last):
  File "/home/mmw/Projects/otel-test/app.py", line 84, in <module>
    SQLAlchemyInstrumentor.instrument(db.engine)
  File "/home/mmw/.virtualenvs/otel-test/lib/python3.9/site-packages/opentelemetry/instrumentation/instrumentor.py", line 97, in instrument
    if self._is_instrumented_by_opentelemetry:
AttributeError: 'Engine' object has no attribute '_is_instrumented_by_opentelemetry'
```

```python
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
db = SQLAlchemy(app)

SQLAlchemyInstrumentor.instrument(db.engine)
```

Looking at the code that should work, I'll take it up with the OTLP folks as well, but if there's anything obvious going on here that you can see I'd love to hear about it!
