### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by racterub** [pallets/flask-sqlalchemy#1031]
SQLAlchemy 1.4 includes [async support](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html). Can this be used from Flask-SQLAlchemy?

**Comment by davidism** [comment]
It is not a huge change to enable this, but it will probably not happen for quite some time. You can already override the engine and session method of the extension to return whatever you want, so it's already possible to get this. The extension itself doesn't need any async code, it only needs to return async engine and session objects.

**Comment by racterub** [comment]
@davidism Thanks for the reply and yes I've already considered to manually overide the engine.
I just think it will be great to add this feature to flask-sqlalchemy, just my own thought :)
