### ISSUE TITLE
Reconsider adding type hints

### ISSUE THREAD

**Issue by marksteward** [pallets/flask-sqlalchemy#1037]
I've read https://github.com/pallets/flask-sqlalchemy/issues/999, and I think it's worth adding. It's currently not possible to automatically hint anything that uses `db.Model`, which means most interesting Flask applications. SQLAlchemy has started adding typing to the main library now.

From trying to write a stub, https://github.com/pallets/flask-sqlalchemy/blob/818c947/src/flask_sqlalchemy/__init__.py#L99-L103 is the fiddly bit. I'm not really sure how to fix that in a concise way that a type checker will understand.

Did you have a plan for this? Happy to help out if possible.

**Comment by davidism** [comment]
See previous linked response, I might do it eventually but don't want to keep an issue open about it.
