### ISSUE TITLE
Using ShardedSession with flask-sqlalchemy

### ISSUE THREAD

**Issue by malicustommade** [pallets/flask-sqlalchemy#130]
Hi,

I'm looking into using a custom session, the SQLAlchemy ShardedSession, but I don't think there's a simple way to do that so far.

DasIch (Daniel Neuhäuser) in #pocoo mentioned that you'd probably do this by modifying `create_scoped_session()` in the flask-sqlalchemy `SQLAlchemy` class.

This function uses `_SignallingSession`. I'm looking at the `_SignallingSession` here: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy.py#L156 and it doesn't seem to do too much other than manage the binds. The other class is here: https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/ext/horizontal_shard.py

I'd love to submit a patch to add sharding support but there's a few ways we could handle this:

1) Don't implement this at all but instead allow people to pass in their own session class, and provide a decorator that wraps their custom `get_bind()` to do the right thing, which they have to use. This is more flexible but less batteries-included.
2) Merge these two together: Write our own `ShardedSession`/`SignallingSession` hybrid to handle the binds properly. But now we have to maintain it, which is probably a miniscule amount of work really.
3) Do both: use 1 with 2

Also, designwise, I'm not sure if the binds in each paradigm mean the same thing. I guess it could be that you can specify binds as you do now, but you can also specify that certain shards are comprised of certain binds. So then if you specify a bind, it'll query only that. If you specify a shard, it'll know to query all the sub-binds. Does this sound reasonable?

Anyone have any guidance?

**Comment by rsyring** [comment]
This should get taken care of by: https://github.com/pallets/flask-sqlalchemy/issues/438
