### ISSUE TITLE
Document benefits/differences to using Flask-SQLAlchemy over plain SQLAlchemy

### ISSUE THREAD

**Issue by yang** [pallets/flask-sqlalchemy#163]
Just a suggestion as I don't think this is actually written down anywhere.  The only obvious savings are that you needn't specify `__tablename__`, define a scoped session, or call `commit`.  (It would be even more awesome to document trade-offs and side effects of using Flask-SQLAlchemy vs plain SQLAlchemy, e.g. #162.)

**Comment by michael-wise** [comment]
When I first started coding, I was using psycopg2 a lot. Finding Flask-SQLAlchemy allowed me to make a ton of progress on my projects in a lot less time (for real, it was great).  So, it may be quite beneficial to the world if Fsqla is more explicit about being a low-barrier-to-entry for new or inexperienced coders. 

This guide would help with that purpose through teaching, promoting/driving traffic to Fsqla, and furthering coders' capabilities. I imagine it would also help with people who want to navigate&contribute to Fsqla or sqla.

**Comment by rsyring** [comment]
For anyone using Flask, I feel like the benefits are obvious.  Given the backlog of issues, I'm going to close this as YAGNI.

**Comment by cal97g** [comment]
@rsyring I'd argue that the benefits are not obvious. In addition to this, many stackoverflow questions are tagged `sqlalchemy` and may only actually be relevant to `flask-sqlalchemy`. A short list of what Flask-SQLAlchemy actually does for you, what 'magic' is actually taking place, would be very nice.

This way we can decide if content is relevant to raw sqlalchemy or only relevant to Flask-SQLAlchemy and we won't have to dive into the codebase.
