### ISSUE TITLE
specifying schema name in model gives error

### ISSUE THREAD

**Issue by lovesh** [pallets/flask-sqlalchemy#172]
I created a model like this. Here i am using a different schema than `public` and my schema is named `schema_name`

``` python
class Region(db.Model):
    __tablename__ = 'regions'
    __table_args__ = {'schema': 'schema_name'}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    parent_id = db.Column(db.Integer, db.ForeignKey('regions.id'))
    parent = db.relationship('Region', primaryjoin=('Region.parent_id==Region.id'), backref='sub-regions')
    created_at = db.Column(db.DateTime, default=db.func.now())
    deleted_at = db.Column(db.DateTime)
```

and it gave me error `sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'regions.parent_id' could not find table 'regions' with which to generate a foreign key to target column 'id'`

But when i remove the line `__table_args__ = {'schema': 'schema_name'}` and use the `public` schema, the code works.
Have a look [here](http://stackoverflow.com/questions/20830147/unable-to-create-self-referencing-foreign-key-in-flask-sqlalchemy)

**Comment by immunda** [comment]
@lovesh any feedback before I close this?

**Comment by Wendong-Wu** [comment]
I think the problem will come when you have defined the `__bind__` and try to create a foreign key to which is in the other schema. 

```python
class Children(db.Model):
    __tablename__ = 'children_table'
    __bind_key__ = 'kids'

    child_id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(Integer, ForeignKey('adults.parent_table.parent_id'), nullable=False)
    name = Column(String(255))
```

**Comment by kblomqvist** [comment]
According to above comment this may be related to #222.

**Comment by davidism** [comment]
As shown in the comment above, you need to include the schema in the foreign key, that's a SQLAlchemy requirement.
