### ISSUE TITLE
Provide documentation for native use of SQLAlchemy signals

### ISSUE THREAD

**Issue by immunda** [pallets/flask-sqlalchemy#274]

**Comment by rsyring** [comment]
SQLAlchemy provides great documentation on signals.  What exactly would FSA be documenting?

**Comment by davidism** [comment]
I think this was in response to our work fixing and deprecating `SQLALCHEMY_RECORD_QUERIES` and `SQLALCHEMY_TRACK_MODIFICATIONS`, respectively. I'm not sure what exactly we wanted to document though, I think we may have discussed it in issue comments.
