### ISSUE TITLE
configure() explodes

### ISSUE THREAD

**Issue by revmischa** [pallets/flask-sqlalchemy#403]
Calling `db.session.configure(expire_on_commit=True)` in the latest version in git blows up:

```
self = <sqlalchemy.orm.scoping.scoped_session object at 0x10c1c1190>
kwargs = {'expire_on_commit': True}

    def configure(self, **kwargs):
        """reconfigure the :class:`.sessionmaker` used by this
            :class:`.scoped_session`.

            See :meth:`.sessionmaker.configure`.

            """

        if self.registry.has():
            warn('At least one scoped session is already present. '
                 ' configure() can not affect sessions that have '
                 'already been created.')

>       self.session_factory.configure(**kwargs)
E       AttributeError: 'functools.partial' object has no attribute 'configure'

../../.virtualenvs/jb/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py:110: AttributeError
```

**Comment by Budulianin** [comment]
I've found this bug and I have fix for this.

**Comment by Budulianin** [comment]
Please, update PYPI and close this issue.

**Comment by rduplain** [comment]
I am looking into making a new release. The project is currently set to 3.0-dev, but this would be a 2.2 release, as the only changes I see are fixes and clarifications. @mitsuhiko +1?

**Comment by davidism** [comment]
I haven't had time to review the current state of the repo in a while, but as long as all the tests are passing and the changelog is updated then we should be fine.

**Comment by rduplain** [comment]
All tests are passing.
https://travis-ci.org/mitsuhiko/flask-sqlalchemy/builds/164926471

The plan is to review the CHANGES file, update references from 3.0 to 2.2, then cut a 2.2 release against what is currently in master.

**Comment by rsyring** [comment]
Release 2.3 is out.  I'm assuming, since the fix was in master, that this issue has therefore been resolved.  If not, feel free to correct me and I'll re-open this issue.
