### ISSUE TITLE
docs/_themes git submodule is pointing to outdated location

### ISSUE THREAD

**Issue by aldanor** [pallets/flask-sqlalchemy#433]
In `.gitmodules`:

``` ini
url = https://github.com/mitsuhiko/flask-sphinx-themes.git
```

should be now changed to

``` ini
url = https://github.com/pallets/flask-sphinx-themes.git
```

otherwise recursive clones fail.

**Comment by davidism** [comment]
I'm working on making flask-sphinx-themes installable.  Once that happens we can get rid of the submodule completely.  Does this only need to be fixed in master?  I'm not very familiar with submodules or recursive clones.

**Comment by aldanor** [comment]
I don't think there's any special process, the `.gitmodules` could be just removed then from the repo when the dependency becomes available as an installable package.

**Comment by davidism** [comment]
I guess I just forgot to close this, but this has been fixed for a while.
