### ISSUE TITLE
API documentation and SQLAlchemy example on versioning

### ISSUE THREAD

**Issue by TrilceAC** [pallets/flask-sqlalchemy#452]
It seems to me that the [API documentation](http://flask-sqlalchemy.pocoo.org/2.1/api/) that talks about the SQLAlchemy versioning example should be fixed or updated. It talks about `VersionedMeta` and `VersionedListener` classes. They no longer exist on the [SQLAlchemy documentation on versioning example](http://docs.sqlalchemy.org/en/latest/orm/examples.html#versioning-objects). See [history_meta.py](http://docs.sqlalchemy.org/en/latest/_modules/examples/versioned_history/history_meta.html) on SQLAlchemy 1.1.4 too.

Looking for some information on those classes I have found [an implementation](http://nullege.com/codes/show/src@k@i@kitsune-HEAD@vendor@packages@sqlalchemy@examples@versioning@history_meta.py/5/sqlalchemy.orm.interfaces.SessionExtension) that have them, but it seems to be an old one because `VersionedListener` inherits from `SessionExtension`, but according to [SQLAlchemy documentation](http://docs.sqlalchemy.org/en/latest/orm/deprecated.html#sqlalchemy.orm.interfaces.SessionExtension), `SessionExtension` is deprecated.

In order to use versioning, I have done something similar* to this:
```
from history_meta import versioned_session

app = Flask(__name__)
db = SQLAlchemy(app)
versioned_session(db.Session)
```
I haven't tested this thoroughly, but this seems to work on my firsts tests. Hopefully I haven't made a big mistake.

(*) Note: I say similar because in fact I'm using a derived class from `SQLAlchemy`, so that I can use pure SQLAlchemy models that are not tied to Flask following an updated [recipe by Derrick Gilland](http://derrickgilland.com/posts/demystifying-flask-sqlalchemy/) @dgilland. I'm also writing a custom `history_meta` that also tracks the creator of each version by means of a callable function passed through a param, but in essence, both are mainly similar to the original class / module.

**Comment by davidism** [comment]
This doesn't appear to be in the docs anymore.
