### ISSUE TITLE
Create SQLite files in instance folder

### ISSUE THREAD

**Issue by davidism** [pallets/flask-sqlalchemy#462]
Flask now encourages devs to make their apps installable from the start. Creating files in the root path goes against this pattern. If the SQLite database is a relative path, it should be relative to the instance path, not the root path. If the instance folder doesn't exist, it should be created.

See #441 for some previous discussion.

Since this would break existing relative paths, I'm marking this for 3.0, and am open to discussion in the meantime.

**Comment by mitsuhiko** [comment]
Still want to do this, expected this to work :)

**Comment by michael-wise** [comment]
The URI is the only part of the quickstart example that isn't platform agnostic. It would be nice to provide a default behavior that creates an sqlite in your python cwd, such as `app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:.'` or `sqlite:` or just `sqlite`.
