### ISSUE TITLE
Make it easy to parse a Pagination object to dict

### ISSUE THREAD

**Issue by italomaia** [pallets/flask-sqlalchemy#482]
Being able to easely parse a Pagination object to dict would make it much more "ajax" friendly.

**Comment by kalombos** [comment]
Hello, i want to contribute but i didn't understand what you need. You want to realize additional method at Pagination class  something like this:
```
def as_dct(self):
    return dict(items=self.items, page=self.page...)
```
?
Please give me more information and i will try to realize it. Thank you.

**Comment by ThiefMaster** [comment]
Not `dct` for sure. That abbreviation is only OK when the name would be `dict` otherwise (and thus shadow the builtin). I'd go for something like `to_dict` or `as_dict`.

**Comment by protream** [comment]
We can do it like this:

```
Class Pagination:
    ...

    def __getitem__(self, key):
        return getattr(self, key)

    def keys(self):
        return ('page', 'pages', 'total', 'has_prev', 'next_num', 'has_next')
```
Now, `dict` a Pagination Object jus do:

data = dict(pagination)
data['items'] = ...

**Comment by spyoungtech** [comment]
Wouldn't it be most appropriate to implement a `__iter__` for this? That way one can simply do `dict(my_pagination_object)`

**Comment by nicolashahn** [comment]
@protream's implementation as a PR: https://github.com/mitsuhiko/flask-sqlalchemy/pull/580

**Comment by rtilk89** [comment]
@jab @davidism - I'm interested in giving this issue a shot, but looks like there is an unmerged PR. Is this still open for contributions?

**Comment by tomowind** [comment]
@rtilk89 I was reading two unmerged PRs #485 and #580. #485 doesn't address comments fully, and #580 doesn't seem to incorporate comments in #485. So, you may extend #580 with tests and addressing comments in #485?

You can work on this one. I will do another.

**Comment by davidism** [comment]
The problem with an `as_dict` method is that it does not guarantee that the result will be serializable by `jsonfiy` or `json.dumps`. Result rows can contain types that are not handled by the default JSON serializer, and it gets even worse when querying models, and it gets even worse when those models are not simple but use the multitude of features available to SQLAlchemy.

The direct way for a dev to handle this, although not the most powerful, is to implement their own `Flask.json_encoder` class to handle the things that would appear in `Pagination.items`. So if we do add a `to_dict` method, it needs to clearly explain that the developer still needs to do something else.

We do not want to take on maintaining a serialization library for result rows or SQLAlchemy models. This is better handled by a serialization library such as Marshmallow, Marshmallow-SQLAlchemy, and Marshmallow-Flask, or another API extension. At which point, that can also handle serializing a `Pagination` object, along with any other API data, at which point `to_dict` isn't needed.

**Comment by davidism** [comment]
Closing based on above comment and discussion in #748.
