### ISSUE TITLE
Seeing a memory leak during testing setup and teardown

### ISSUE THREAD

**Issue by cmanallen** [pallets/flask-sqlalchemy#524]
When setting up and tearing down tests I'm seeing a large memory leak that I've partially tracked to flask-sqlalchemy.  I removed the flask-sqlalchemy package and saw ~60% of the leak disappear.

`_DebugQueryTuple` was the fastest growing type (of any type).

### System information:

* I'm running this on a Python 3.5 docker container.
* Information was collected using `objgraph`.

Commands used:

```bash
tty1 $ docker-compose run container nosetests -w tests
---
tty2 $ docker stats
```

Test suite setup and teardown methods:

```python
def setUp(self):
    """Create app test client."""
    self.app = self._create_app()
    self.app_context = self.app.app_context()
    self.app_context.push()
    self.client = self.app.test_client()
    db.create_all()
    db.session.commit()

    self.addCleanup(self.cleanup)

def cleanup(self):
    """Tear down database."""
    db.session.remove()
    db.drop_all()
    db.get_engine(self.app).dispose()
    self.app_context.pop()
```

**Comment by makmanalp** [comment]
Perhaps related: #181 / #186

**Comment by makmanalp** [comment]
Perhaps this will help narrow it down a bit: I've had a similar experience where I have a script that ingests some data into a database with pandas' `.to_sql` function, but when I pass it the SQLAlchemy engine from flask-sqlalchemy, it runs out of memory quickly even though I specify `chunksize=` (data is much larger than memory). If I create my own fresh sqlalchemy engine from scratch, the issue doesn't seem to happen and memory usage seems to stay at a reasonable size relative to my chunksize.

**Comment by makmanalp** [comment]
(Admittedly my use case is weird, it involves inserting hundreds of millions of rows which I suspect exacerbates the problem, but hoping it'll be helpful in diagnosing the issue above)

**Comment by davidism** [comment]
Do you see the issue if you disable `DEBUG` and `SQLALCHEMY_RECORD_QUERIES`?

**Comment by makmanalp** [comment]
In my case, yes.

**Comment by assafsch** [comment]
I was experiencing the same issue, but managed to overcome it by setting both ```DEBUG``` and ```SQLALCHEMY_RECORD_QUERIES``` to ```False```

**Comment by davidism** [comment]
Closing as I'm not really sure what to do about this, or if it's even something Flask-SQLAlchemy can control.
