### ISSUE TITLE
Query object re-use

### ISSUE THREAD

**Issue by orenmazor** [pallets/flask-sqlalchemy#566]
I'm trying to do some cleanup on a codebase I just inherited, so I'm not 100% on top of SQLAlchemy yet.

I can see that flask-sqlalchemy makes sure that `db.session` is managed by the request lifecycle, which is great. 

But my codebase is still full of basically `Foo.query.get(1)` type of behaviour, which appear to spin up entirely new connections every time (confirmed via newrelic showing 50-60% of my request times are just rollbacks on connection checkouts/checkins).

I'd like to have just one connection per request (or even if I could force a single connection in a context block somehow) to avoid a huge performance hit when I'm returning a few hundred objects in a view. 

Currently 100 objects generates 100 connection checkouts and rollback, which is problematic.

Whats the idiomatic way of doing it here? I can obvious go in and change every `Foo.query.get` to be a `db.session(Foo)` type stuff, but thats a lot of code flux.

**Comment by orenmazor** [comment]
@ThiefMaster yeah, assume there's nothing in the identity cache, so 100% going to the db.

my issue is that the check-in of a connection to a pool issues a ROLLBACK to myqsl which ends up being death by a thousand cuts for me. why do I check in a connection when I know I need to query more?

I agree that this specific situation can be an `in_` query. I'm asking for the hypothetical case where I'd like to not be checking in the connection when I know I need to do more selects

**Comment by ThiefMaster** [comment]
within a single db session there shouldn't be any rollbacks

**Comment by orenmazor** [comment]
right, but it looks like every time I do `Foo.query.get` I end up checking out a new connection. I added a breakpoint on a listener for checkout/checkin and I'm just seeing a new checkout for each of these:

`Foo.query.get(1)`
`Bar.query.get(1)`
`Waldo.query.get(1)`

and because each results in a check-in of a connection, sqlalchemy issues a ROLLBACK

**Comment by ThiefMaster** [comment]
that seems strange. could you provide a small standalone script demonstrating the problem?

**Comment by samuelharmer** [comment]
This wouldn't be anything to do with [autocommit](http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#autocommit-mode) would it?

**Comment by davidism** [comment]
That's not enabled in Flask-SQLAlchemy.

**Comment by orenmazor** [comment]
> This wouldn't be anything to do with autocommit would it?

We actually do have autocommit enabled. I think we actually have several paradigms of db use happening (because some things run in flask, some run in background jobs without a flask request context). I just need to figure out how to make sure the ones that run in the requests are using the db in the more optimal way.

I'll try to get a standalone app put together for you guys to look at.
