### ISSUE TITLE
Add use_batch_mode parameter to sqlalchemy create_engine

### ISSUE THREAD

**Issue by argolo** [pallets/flask-sqlalchemy#594]
I would like to add use_batch_mode parameter or sqlalchemy create_engine. Is there something that allows this or can I work on a pull request? What would be the best approach in the case of pull request?

Source on use_batch_mode:
 - http://docs.sqlalchemy.org/en/latest/changelog/migration_12.html#dialect-improvements-and-changes-postgresql
 - http://initd.org/psycopg/docs/extras.html#fast-execution-helpers
 - https://stackoverflow.com/questions/38369569/insert-data-into-postgresql-from-python

**Comment by nirizr** [comment]
Hi, I came across this issue and I'd like to express my interest in this functionality.

**Comment by nirizr** [comment]
Hi,
I also have that issue and I would also like it fixed, but in the meanwhile I found a simple work-around that helped me.

by accessing the engine's dialect you can manually set the member responsible for using the match_mode after the engine and dialect have been created. Assuming `db = SQLAlchemy(flask_app)`, all you need to do is add the following line afterwards:

`db.engine.dialect.psycopg2_batch_mode = True`

**Comment by moi90** [comment]
Thanks @nirizr !

However, Flask-SQLAlchemy should really allow passing keyword parameters to create_engine. The simplest solution would be a configuration key, right?

**Comment by nirizr** [comment]
Yes. Probably. This is a workaround, not a fix :)

**Comment by grim7reaper** [comment]
Hi,

I also had the need to specify extra kwargs to the underlying call to `create_engine` (to be more specific, I needed to customize the isolation level).

To do so, I used the method `apply_driver_hacks` (documented [here](http://flask-sqlalchemy.pocoo.org/2.3/api/#flask_sqlalchemy.SQLAlchemy.apply_driver_hacks)):

> This method is called before engine creation and used to inject driver specific hacks into the options. The options parameter is a dictionary of keyword arguments that will then be used to call the sqlalchemy.create_engine() function.

What you need to do is to define your own class that overload this method:

```python
class SQLAlchemyCustomized(flask_sqlalchemy.SQLAlchemy):
    def apply_driver_hacks(self, app, info, options):
        options['use_batch_mode'] = True
        super().apply_driver_hacks(app, info, options)
```

And then use your class instead of the default one:

```python
# Replace "db = SQLAlchemy(app)" by
db = SQLAlchemyCustomized(app)
```

Hope that helps :)

**Comment by rsyring** [comment]
This will be resolved by: https://github.com/pallets/flask-sqlalchemy/issues/166
