### ISSUE TITLE
Support passing third party connection instance to Flask-sqlalchemy db constructor or objects

### ISSUE THREAD

**Issue by yiakwy** [pallets/flask-sqlalchemy#635]
# SQLAlchemy engine construction

SQLAlchemy allows users to pass connection created by third-party clients instead of specifying database url to construct a connection to remote.

For example, if I want to connect to Hive, of which configuration is a little bit complicated. SQLAlchemy allows users to create engine by

```python
engine = sqlalchemy.create_engine('impala://', creator=conn)
```

Where "impala" from *cloudera* is an implementation of Hive2 client. 

However in the current implementation, only URL string accepted.

# More Problems

The buggy implementation (not aligned to original ORM specification) will also create errors when people try to bind to multiple backends:

[] hadoop,
[] hive
[] nosql
[] sql

We have to seek different suppliers solution to trackle that problem.

**Comment by rsyring** [comment]
The solution I propose at https://github.com/pallets/flask-sqlalchemy/issues/166#issuecomment-470711632 will solve this as it will give you complete control over how to create your engine.
