### ISSUE TITLE
Maximizing the impact of Flask-SQLAlchemy 

### ISSUE THREAD

**Issue by michael-wise** [pallets/flask-sqlalchemy#641]
Intro: When I first started coding, I was using psycopg2 a lot. Finding Flask-SQLAlchemy allowed me to make a ton of progress on my projects in a lot less time (for real, it was great). So, it may be quite beneficial to the world if Fsqla is more explicit about being a low-barrier-to-entry for new or inexperienced coders.

Purpose: I started this issue to gauge interest and gather ideas (pain points) for further lowering Fsqla's barrier to entry for inexperienced coders (kudos for how easy it already is). So, particularly, getting rid of often-encountered hurdles in usage or docs. Sometimes, very small changes can have a large impact (see proposal 1). Pain points that get support can get issues.

Conclusion: It may be argued that it is tedious and verbose to cater too much to new users. That is a possibility. Yet, it is possible to be clear and informative while not bloating things up. And secondly, it may be considered a moral obligation to support new coders in such a useful/easy framework as Fsqla.

1)  "Quickstart: A minimal Application" page doesn't speak about the `SQLALCHEMY_DATABASE_URI` uri `'sqlite:////tmp/test.db'`. It undoubtedly sends many people to google for one reason or another (certainly windows users, because copy/paste doesn't work). A link to [doc: config/#Connect-Uri-Format](http://flask-sqlalchemy.pocoo.org/2.3/config/#connection-uri-format) would go a long way.
.
From a newbie perspective: [1] `////` is not commonly encountered. [2] It is ambiguous whether `tmp/test.db` is a relative path or absolute path. [3] The nature of test.db is unclear--is it created automatically? [4] Is sqlite something that needs to be installed? Python includes it already, but what do I need to know about that? [5] How can I easily/quickly view my test.db to see what's in it? A recommended tool?
.
#469 mentions amending quickstart.
#462 intends to make the uri relative to cwd by default, but suggested for 3.0. In there, I suggest allowing `sqlite` alone to be a valid uri.

2) #163 Document benefits/differences to using Flask-SQLAlchemy over plain SQLAlchemy. 

3) #502 A note/reminder for users exploring their Postgres db from CLI/via queries. It's interesting and informative to people who don't know. https://github.com/mitsuhiko/flask-sqlalchemy/pull/502/commits/4db21106fa6c494a435277f0749e58937de284f1

4) For the Version subsection in the left-panel of pocoo site, have the current version you're viewing display the entire documentation overview (as it currently is, the Related Topics subsection instead displays the previous and next topic).

5) ?

**Comment by michael-wise** [comment]
whoops accidentally submitted. Adding a description now.

**Comment by davidism** [comment]
1. will be handled by #462 
2. is not really in scope, but I'll keep it in mind when updating the readme / docs index.
3. is not really in scope, and I don't think the note belongs where you added it in that commit, but if you want to put it *somewhere* and submit a PR, go for it
4. version section will change, but that's not something that can be tracked here
5. ?

Thanks for your feedback. We'll keep it in mind while updating the docs.
