### ISSUE TITLE
Allow binding of query_class in init_app

### ISSUE THREAD

**Issue by dusktreader** [pallets/flask-sqlalchemy#664]
Currently, you need to specify your query_class at construction time.

I use the app factory pattern, and, to avoid circular import problems, I import auxillery classes like my custom query class within the create_app method of that factory. This doesn't work well with flask-sqlalchemy because the query_class is bound at initialization time instead of at init_app time.

If that binding could happen later or a new binding created in init_app, it would be really helpful.

**Comment by davidism** [comment]
That would require a significant refactor of how `query_class` is applied. I've used a custom query class with the app factory before and haven't had an issue. Could you provide an example that would be fixed with this change?

**Comment by dusktreader** [comment]
In this case, it's because one of my custom query class methods needs to import one of my core models (to allow the fluent API to work seamlessly), and that import has the side effect of an unruly circular import problem.

My use-case is probably way off the beaten path for most projects (probably because it's an ill-advised idea). Still, I'm used to most flask extensions doing the heavy lifting of initialization in the init_app method instead of in the class constructor.

**Comment by justanr** [comment]
The problem with that is the query class is used as part of the model class generation. If you're willing to sacrifice the SQLAlchemy.Model usage you could use the mapper API and bind to SQLAlchemy.Table with that.

https://github.com/justanr/gamenight/blob/master/src/gamenight/app/repository/game.py

If you scroll down to the configure method (sorry on mobile) that's an example of it.

**Comment by rsyring** [comment]
Sorry, sounds like this is not something we are going to be able to support.  Sorry.
