### ISSUE TITLE
Deprecation Warning with SQLAlchemy 1.3 beta

### ISSUE THREAD

**Issue by crcornwell** [pallets/flask-sqlalchemy#671]
This is probably a bit premature, but when using SQLAlchemy 1.3.0b2 I encountered a deprecation warning at https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L157.

This can be easily addressed by replacing
```
info = getattr(mapper.mapped_table, 'info', {})
```
with:
```
info = getattr(mapper.persist_selectable, 'info', {})
```

Also, what are the plans for updating for 1.3 compatibility in general?

**Comment by sbv-trueenergy** [comment]
And now it's released and quite noisy

``` xx passed, xxx skipped, 7300 warnings``` from my test-suite that used to be warnings free

**Comment by rsyring** [comment]
Their are commits in #684 that resolve this issue.

**Comment by jakeczyz** [comment]
This SADeprecationWarning (`/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:157: SADeprecationWarning: Use .persist_selectable`) has been polluting our log files for days.  

I'm super grateful to the volunteers that keep this package usable for the ecosystem.   Just wondering when this may be merged, and/or is there anything specific holding it back? :)

**Comment by rsyring** [comment]
The fix is in: https://github.com/pallets/flask-sqlalchemy/pull/684

I've been waiting for approval on that PR.  As soon as I get or get some kind of response, I'm hoping to get a release out soon.

**Comment by halfdan** [comment]
@rsyring Looks like it's approved - thanks for putting in the effort to keep this package up to date for us.
