### ISSUE TITLE
Wiki pages down

### ISSUE THREAD

**Issue by Chaostheorie** [pallets/flask-sqlalchemy#676]
All pages are searchable but after try to open one of them a 404 of nginx is raised and the pages are not viewable. Seems like the pages could not be found but the indices in the db are online. 
Page: http://flask-sqlalchemy.pocoo.org/2.3/
The page was opened from germany

**Comment by davidism** [comment]
That page opens fine for me.

**Comment by greyli** [comment]
Something was wrong in the search page. When you search something, all the result items' disgest show the source of 404 page:

![image](https://user-images.githubusercontent.com/12967000/53060990-47f02e00-34f7-11e9-8cdf-1513fbd7c391.png)

Click the result link will got the Nginx 404 page:

![image](https://user-images.githubusercontent.com/12967000/53061016-68b88380-34f7-11e9-8641-1d3fdba78ca7.png)

IMO, this problem result from the redundant "/search" part in the result URL (see image above), remove it you will get the correct page.
