### ISSUE TITLE
Documentation search page render invalid link for results

### ISSUE THREAD

**Issue by greyli** [pallets/flask-sqlalchemy#677]
Something was wrong in the search page. When you search something ( http://flask-sqlalchemy.pocoo.org/2.3/search/?q=model ), all the result items' disgest show the source of 404 page:

![image](https://user-images.githubusercontent.com/12967000/53060990-47f02e00-34f7-11e9-8cdf-1513fbd7c391.png)

Click the result link will got the Nginx 404 page ( http://flask-sqlalchemy.pocoo.org/2.3/search/models/?highlight=model ):

![image](https://user-images.githubusercontent.com/12967000/53061016-68b88380-34f7-11e9-8641-1d3fdba78ca7.png)

IMO, this problem result from the redundant "/search" part in the result URL (see image above), remove it you will get the correct page ( http://flask-sqlalchemy.pocoo.org/2.3/models/?highlight=model ).

**Comment by WoLpH** [comment]
I've seen this bug on many sites using the readthedocs on custom (sub)domains. A workaround is to use the readthedocs subdomain instead: https://flask-sqlalchemy.readthedocs.io/en/stable/

**Comment by davidism** [comment]
Assigning myself since I mainly just need to get the docs config standardized like I'm doing with the rest of the Pallets projects, then I can update the RTD build.

**Comment by davidism** [comment]
Will be fixed in the next release.
