### ISSUE TITLE
Best way to import Initial Data to some tables

### ISSUE THREAD

**Issue by bcochofel** [pallets/flask-sqlalchemy#678]
Hi all,

I have some tables that I want to have some initial values because of some dependencies.
I've tried using event.listens_for on 'after_create' but that's starting to get a bit messy «cause I need lots of data. 
I was thinking of having something like .csv files with the values I want to ensure that exist on some table but I don't know if this is the best method.

What should I use for this? The most efficient way to ensure everytime I run the app that those values exist on some tables.

Thanks,
Bruno

**Comment by ThiefMaster** [comment]
Just add a cli command to your app that does it, either together with calling `db.create_all()` or as a completely separate command.
