### ISSUE TITLE
More restrictive version lock of SQLAlchemy in setup.py

### ISSUE THREAD

**Issue by nickjj** [pallets/flask-sqlalchemy#680]
I just installed Flask-SQLAlchemy 2.1 today (part of an older code base) but it pulled down SQLAlchemy 1.3.0 which is brand new. SQLAlchemy 1.3.0 has a number of backwards incompatible changes with 1.2 and previous releases which is wreaking havoc in a code base.

A big one is:

_[sql] [bug] Fully removed the behavior of strings passed directly as components of a select() or Query object being coerced to text() constructs automatically; the warning that has been emitted is now an ArgumentError or in the case of order_by() / group_by() a CompileError. This has emitted a warning since version 1.0 however its presence continues to create concerns for the potential of mis-use of this behavior._

The expected behavior IMO would be that Flask-SQLAlchemy version locks something more specific in setup.py for SQLAlchemy and then you can manage bumping it up with new Flask-SQLAlchemy releases.

Right now it just pulls in versions >= 0.8.0 which is very dangerous.

**Comment by ThiefMaster** [comment]
`<1.3` would probably have made sense, but now i think we should just fix whatever is broken and lock to `<1.4`

**Comment by davidism** [comment]
Are the changes causing issues with Flask-SQLAlchemy or your code?

**Comment by davidism** [comment]
I do not want to use `<` specifiers if at all possible because this would mean users are locked out of new versions until Flask-SQLAlchemy makes a release. I would be OK just bumping the minimum version.

**Comment by nickjj** [comment]
It's causing issues with my code base due to Flask-SQLAlchemy not really version locking SQLAlchemy.

It's pretty easy to fix it by explicitly putting SQLAlchemy==1.2.0 in my requirements.txt and rebuilding, but it's never that simple because I didn't have the foresight to do that 1.5 years ago and now thousands of people who are taking my Flask course are starting to report that the code is broken since when they build the project today, they are getting SQLAlchemy 1.3.x.

I know this isn't your problem, but I do think it's a good idea to version lock SQLAlchemy at the Flask-SQLAlchemy level because otherwise rebuilding an app with the same Flask-SQLAlchemy version can produce different results.

**Comment by davidism** [comment]
If it's an issue with how you're using SQLAlchemy, that's a version requirement you should specify in your project.

**Comment by rsyring** [comment]
To expand on David's question: do Flask-SQLAlchemy's tests fail with the new version of SA?  Or does your application just have issues with it?

If the former, it's a bug we need to fix.  If the latter, it would be up to you to specify the needed versions at the application level.  More details:

https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by rsyring** [comment]
Closed since it sounds like an application level specification is what you need.

**Comment by davidism** [comment]
I don't have context to how your Flask course is presented, is there no way to issue an update? Gating the maximum SQLAlchemy version behind Flask-SQLAlchemy releases doesn't make sense unless a SQLAlchemy version is directly affecting Flask-SQLAlchemy.

**Comment by nickjj** [comment]
An update is possible but now the source code won't match the videos so I need to go and add notes to reflect the change and then update it in 7 or 8 different spots (each section of the course is standalone and has its own requirements.txt).

> Gating the maximum SQLAlchemy version behind Flask-SQLAlchemy releases doesn't make sense unless a SQLAlchemy version is directly affecting Flask-SQLAlchemy.

With the way things are set up in your `setup.py`, you do get the latest SQLAlchemy version, which is pretty unexpected IMO.
