### ISSUE TITLE
Supported Python and dependency versions

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#685]
I'd like to get a version support matrix defined and documented.  Currently, tox is setup to run

* Python 2.6, 2.7, 3.3-3.6, pypy w/ Flask and SA at their latest released versions
* Some of those same versions w/ Flask 0.10 and SA 0.8

I would assume support for 2.6 and 3.3 should be able to be dropped considering tox won't even run those versions.  See: https://github.com/pallets/flask-sqlalchemy/pull/684

However, can we "officially" do that without a major point release?  refs: #682

**Comment by davidism** [comment]
Drop Python 2.6 and 3.3, add 3.7, see Werkzeug for example. 3.4 ends in a few months. It's fine to drop versions in 2.4.

Should only need one env for lowest versions.

Flask <0.12 is not supported, but I don't think there's any reason not to allow it right now, although 3.0 should probably bump to Flask 1.0. Same with the min version of SQLAlchemy.

**Comment by rsyring** [comment]
#687 will take care of this for the 2.x branch

Leaving open and setting milestone to 3.0 so we remember to make updates for when 3.0 is released.

**Comment by hugovk** [comment]
Python 3.4 is EOL on Saturday (2019-03-16).

https://devguide.python.org/#status-of-python-branches


Here's the pip installs for Flask-SQLAlchemy from PyPI for February 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  41.14% |   393,179 |
|      3.6 |  35.89% |   343,036 |
|      3.7 |  12.73% |   121,637 |
|      3.5 |   8.06% |    77,050 |
|      3.4 |   1.56% |    14,910 |
| null     |   0.53% |     5,105 |
|      2.6 |   0.04% |       424 |
|      3.3 |   0.02% |       219 |
|      3.8 |   0.01% |        99 |
|      3.2 |   0.00% |         8 |
| Total    |         |   955,667 |

Source: `pypistats python_minor Flask-SQLAlchemy --last-month # pip install pypistats`

**Comment by ticosax** [comment]
1st of January 2020, python2 will be officially unsupported.

We need to think how to phase it out. I'm in favour of dropping it as part of next major release as it will ease the maintenance burden of the project by not taking care of compatibility for older versions  (`supported python versions for flask-sqlalchemy >= 3.5`)

**Comment by davidism** [comment]
Phasing out Python 2 is something Pallets will handle.

**Comment by davidism** [comment]
Python 2 support can be dropped on January 1st, 2020, but not before then.

**Comment by rsyring** [comment]
I'm updating the support matrix to drop support for 3.4 for FSA 3.0+.

**Comment by davidism** [comment]
Dropped Python 2, 3.4, and 3.5 in #822 and #826.

**Comment by davidism** [comment]
SQLAlchemy 1.3 is only a year old, so I think it's ok to still support 1.2 minimum, it only requires one workaround in our code. I'll bump Flask minimum to 2.0 once that's released (it will come before FSQLA 3.0 is released), since that will match the Python >= 3.6 requirement.
