### ISSUE TITLE
Travis: nightly & pypy testing.  Still needed?

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#689]
Werkeug & Flask both run CI builds for pypy & Python nightly.  However, the travis config lists both of those in `allow_failures`.  If CI isn't going to fail, why test it in CI at all.  Just leave it as an option in tox?

**Comment by davidism** [comment]
Nightly is to catch any bugs or deprecations in the next version, it's not a problem if it fails. Pypy just takes a long time to collect tasks, so I don't like waiting for it for intermediate builds, and I don't expect it to change for most prs.

I usually just check Travis before merging. And I do run the full tox suite before release.

**Comment by rsyring** [comment]
Sounds good.
