### ISSUE TITLE
Phasing out python2 ?

### ISSUE THREAD

**Issue by ticosax** [pallets/flask-sqlalchemy#694]
1st of January 2020, python2 will be officially unsupported.
How do you plan to get rid of it ? that's something we should think about it, maybe for the 3.0 milestone ?

Also we could think about stop supporting older unsupported versions of python3.
as of today only `>=3.6` makes sense:

> python3.4 September 29, 2017
python3.5 March 17, 2019

https://www.python.org/dev/peps/pep-0398/#x-end-of-life
https://www.python.org/dev/peps/pep-0429/

**Comment by rsyring** [comment]
@ticosax thanks for your comments.  Would you please re-post them on #685.

**Comment by ticosax** [comment]
Sure. sorry double posting
