### ISSUE TITLE
Set SQLALCHEMY_TRACK_MODIFICATIONS to False by default

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#699]

**Comment by lbeaufort** [comment]
Hi @rsyring I'd like to work on this issue if that's ok. 

It looks like all I have to do is update the app config here: https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L832-L834 to match the other config settings, remove the depreciation warnings, and possible look at the other `track_modifications` logic.

**Comment by lbeaufort** [comment]
If that's right, should `test_track_modifications_warning` be removed and `test_defaults` be modified to reflect this new behavior?
