### ISSUE TITLE
Travis isn't building any PRs that are targeting the 2.x-maintenance branch

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#702]
Looks like they aren't building because of our `branches` setting in `.travis.yml`.

Ref: https://docs.travis-ci.com/user/common-build-problems/#i-pushed-a-commit-and-cant-find-its-corresponding-build

For now, appending "-maintenance" onto branch names I'm creating works.  Ideally, we'd be able to tell travis to build any branch that has a PR...but, not going to worry about that at the moment.

**Comment by rsyring** [comment]
appending "-maintenance" causes two builds to get kicked off:

![image](https://user-images.githubusercontent.com/109467/54388762-d8dca400-4674-11e9-998a-0b3b6e03d3c5.png)

We could potentially turn off "build pushed branches":

https://travis-ci.org/pallets/flask-sqlalchemy/settings

But that doesn't seem ideal either.

**Comment by davidism** [comment]
Look at Werkzeug's Travis config. We moved to "2.x" rather than "2.x-maintenance", since that looks better on Read the Docs, then adjusted the branches config.

**Comment by rsyring** [comment]
Will do.

**Comment by rsyring** [comment]
This might just be a problem when PRs are changed to target a different branch as #684 seems to work fine.

**Comment by rsyring** [comment]
Confirmed new PRs are building just fine.
