### ISSUE TITLE
how to create database with flask-sqlalchemy?

### ISSUE THREAD

**Issue by my3188** [pallets/flask-sqlalchemy#704]
how to create database with flask-sqlalchemy? Use only flask-sqlalchemy,not sqlalchemy!

**Comment by ThiefMaster** [comment]
Creating the DB is outside the scope of either SA and FSA. Usually the user your application runs at won't even have the permission to create databases.

And FYI, FSA is just a rather thin wrapper for SA, so "only FSA" is generally not a thing.
