### ISSUE TITLE
Mixed-up names in docs explaining relationships

### ISSUE THREAD

**Issue by pfabri** [pallets/flask-sqlalchemy#706]
I believe that [section detailing relationships](http://flask-sqlalchemy.pocoo.org/2.3/models/#one-to-many-relationships) has a naming mix-up in the model definitions.

**At first there is:**

    class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    addresses = db.relationship('Address', backref='person', lazy=True)

**But further down it changes to this, where backrefs are explained in more detail:**

	class User(db.Model): # this should read: Person(db.Model)...
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(50), nullable=False)
	addresses = db.relationship('Address', lazy='select',
	backref=db.backref('person', lazy='joined'))

I think this is quite misleading and it's easy to think that this is a third table, which somehow connects to the two others defined earlier. It certainly had me confused for a while.

**Comment by rsyring** [comment]
@pfabri thank you for the report.  We will get this fix in the 2.4 release, which should be coming soon.

**Comment by davidism** [comment]
closed in #718
