### ISSUE TITLE
Remove "convert_unicode"

### ISSUE THREAD

**Issue by diogobaeder** [pallets/flask-sqlalchemy#707]
Hi,

The "convert_unicode" argument is being used in flask-sqlalchemy, however it's deprecated in SQLAlchemy:

```
SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
    default.DefaultDialect.__init__(self, **kwargs)
```

So the options here should probably be an empty dict, right?: https://github.com/pallets/flask-sqlalchemy/blob/50944e77522d4aa005fc3c833b5a2042280686d3/flask_sqlalchemy/__init__.py#L558

Thanks,
Diogo

**Comment by rsyring** [comment]
Thanks for the report.  This will be resolved in https://github.com/pallets/flask-sqlalchemy/pull/684.

**Comment by diogobaeder** [comment]
Ah, cool, good to know! Thanks!

(Feel free to close the issue if it's not relevant anymore)
