### ISSUE TITLE
flask本地测试环境无法实时获取数据库中的数据

### ISSUE THREAD

**Issue by Python8888** [pallets/flask-sqlalchemy#708]
线上环境和本地测试环境(werkzeug)都未设置SQLALCHEMY_COMMIT_ON_TEARDOWN但是线上环境可以实时获取数据库中的数据，为什么本地测试环境却无法实时获取。未设置其他的自动提交设置。

**Comment by ThiefMaster** [comment]
Didn't you notice that all other issues are in English? :)
