### ISSUE TITLE
TypeError: ping_connection() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by kdhindsa** [pallets/flask-sqlalchemy#709]
I am migrating my codebase to python 3 and in the process of upgrading versions of dependencies I stumbled upon this error which seems to be originating from Flask-SQLAlchemy. 

The stacktrace is pasted below.

The line that causes this error is the following:

`from flask_sqlalchemy import SQLAlchemy`
`db = SQLAlchemy(app)`
`db.session.remove()`
`db.drop_all()`

db.drop_all() is the one that starts a chain of method calls which eventually results in `fn(*args, **kw)` blowing up because `ping_connection()` is passed the wrong number of arguments.

Stacktrace:

self = <sqlalchemy.event.attr._EmptyListener object at 0x10ef97c18>
args = (<sqlite3.Connection object at 0x10eedaab0>, <sqlalchemy.pool.base._ConnectionRecord object at 0x10eeca0b8>, <sqlalchemy.pool.base._ConnectionFairy object at 0x110a857b8>)
kw = {}, fn = <function ping_connection at 0x10d12e950>

    def __call__(self, *args, **kw):
        """Execute this event."""

        for fn in self.parent_listeners:
>           fn(*args, **kw)
E           TypeError: ping_connection() takes 2 positional arguments but 3 were given

../build/golinks/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py:259: TypeError

**Comment by kdhindsa** [comment]
These are the versions I am using in my python project:

"Flask": "pypi:Flask:1.0.2",
"flask-restplus": "pypi:flask-restplus:0.12.1",
"Flask-Cache": "pypi:Flask-Cache:0.13.1",
"Flask-SQLAlchemy": "pypi:Flask-SQLAlchemy:2.3.1",
"Flask-Testing": "pypi:Flask-Testing:0.7.1",
"Flask-WTF": "pypi:Flask-WTF:0.14",
"PyMySQL": "pypi:PyMySQL:0.9.2",

**Comment by rsyring** [comment]
A full stack trace and MCVE (https://stackoverflow.com/help/mcve) would help us troubleshoot this.

**Comment by kdhindsa** [comment]
[stacktrace.txt](https://github.com/pallets/flask-sqlalchemy/files/3015413/stacktrace.txt)

Attached is the full stacktrace with some internal company information masked.

**Comment by kdhindsa** [comment]
And here is a full list of "external" gradle dependencies:

    "APScheduler": "pypi:APScheduler:3.5.3",
    "Flask": "pypi:Flask:1.0.2",
    "flask-restplus": "pypi:flask-restplus:0.12.1",
    "Flask-Cache": "pypi:Flask-Cache:0.13.1",
    "Flask-SQLAlchemy": "pypi:Flask-SQLAlchemy:2.3.1",
    "Flask-Testing": "pypi:Flask-Testing:0.7.1",
    "Flask-WTF": "pypi:Flask-WTF:0.14",
    "PyMySQL": "pypi:PyMySQL:0.9.2",

    "beautifulsoup4": "pypi:beautifulsoup4:4.5.3",
    "cryptography": "pypi:cryptography:2.0.2",
    "elasticsearch": "pypi:elasticsearch:1.5.0",
    "mock": "pypi:mock:2.0.0",
    "parse": "pypi:parse:1.6.6",
    "python-ldap": "pypi:python-ldap:3.1.0",
    "requests": "pypi:requests:2.21.0",
    "rfc3986": "pypi:rfc3986:0.2.2",
    "statsd": "pypi:statsd:3.2.1"
