### ISSUE TITLE
Support for backup node connection.

### ISSUE THREAD

**Issue by brishi19791** [pallets/flask-sqlalchemy#711]
Hi All,

I have Postgres DB two node cluster and using SQLALCHEMY_DATABASE_URI were we can give only one node details. But how can i achieve a scenario were if the given node goes down SQLALCHEMY will connect to the other backup node. Is there an option of giving the backup node details in SQLALCHEMY_DATABASE_URI?
Thanks in advance,
-Rishi

**Comment by rsyring** [comment]
Issues are not a great medium for support requests.  Please try StackOverflow or similar for these types of requests.  Thanks.
