### ISSUE TITLE
Should flask_sqlalchemy.Model.__init__ be overrideable?

### ISSUE THREAD

**Issue by rascalking** [pallets/flask-sqlalchemy#712]
I have some custom types (json-encoded lists/dicts), but working with newly-created instances of models that include those types can be awkward.  I end up needing to pepper code that deals with those models with a bunch of boilerplate like the following:

```
if instance.field is None:
    instance.field = []
instance.field.append('thing')
```

I've supplied column defaults, but my understanding is those don't come into play until the instance is attached to a session and flushed.  SQLAlchemy's [docs on object initialization](https://docs.sqlalchemy.org/en/latest/orm/constructors.html#constructors-and-object-initialization) suggest that I should be able to override `__init__` on my model to do what I'm trying to do.

To avoid needing to do that for each individual model that uses those types, I wanted to use introspection in my base class.  Which, given that I'm working under flask-sqlalchemy, I thought meant doing it on the class I pass in as my `model_class`.

That doesn't seem to be doing what I expected, and I wanted to see if my expectations are off before I start a code dive to figure out why.

Here's a variation on the quickstart sample from the flask-sqlalchemy docs:

```
from flask import Flask
from flask_sqlalchemy import Model, SQLAlchemy


class BaseModel(Model):
    def __init__(self, *args, **kwargs):
        print('BaseModel.__init__')
        super().__init__(*args, **kwargs)

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app, model_class=BaseModel)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        return '<User %r>' % self.username


class Group(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    groupname = db.Column(db.String(80), unique=True, nullable=False)

    def __init__(self, *args, **kwargs):
        print('Group.__init__')
        super().__init__(*args, **kwargs)
```

When I create a `User` instance, I'd expect to see `BaseModel.__init__` printed.  When I create a `Group` instance, I'd expect to see that as well as `Group.__init__` printed.  Here's what actually happens (python 3.6.7, flask-sqlalchemy 2.3.2, sqlalchemy 1.3.2):

```
>>> from app import *
>>> db.create_all()
>>> user = User()
>>> group = Group()
Group.__init__
>>>
```

**Comment by ThiefMaster** [comment]
You can easily provide a custom class that's exposed as `db.Model`:

```python
from flask_sqlalchemy import SQLAlchemy, Model
from sqlalchemy.ext.declarative import declarative_base

class MyModel(Model):
    pass

db = SQLAlchemy(model_class=declarative_base(cls=MyModel, name='Model'))
```

**Comment by davidism** [comment]
This is a property of how SQLAlchemy creates a declarative base class. Flask-SQLAlchemy allows passing either a simple class or an instance of `declarative_base` to `model=`. When you pass a simple class, it's passed through `declarative_base` to create a model base class. `declarative_base` provides its own `__init__` unless told to do otherwise.

Here's a SQLAlchemy example demonstrating the same behavior.

```python
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base


class Base:
    def __init__(self, *args, **kwargs):
        print("base")
        super().__init__(*args, **kwargs)


Base = declarative_base(cls=Base)


class User(Base):
    __tablename__ = "user"

    id = sa.Column(sa.Integer, primary_key=True)

    def __init__(self, **kwargs):
        print("user")
        super().__init__(**kwargs)


User()
# only "user" is printed, not "base"
```

**Comment by rascalking** [comment]
Ahh, gotcha.  The docs I referenced were working with an individual model class, not the base.  Thanks so much for the quick response!

**Comment by rascalking** [comment]
In case anyone finds this later, the cleanest approach I could find for solving this was to insert it in an abstract subclass of `db.Model`, then use _that_ as the base for my models.

```
db = SQLAlchemy(app)

class MyBase(db.Model):
    __abstract__ = True

    def __init__(self, *args, **kwargs):
        print('MyBase.__init__')
        super().__init__(*args, **kwargs)

class User(MyBase):
    ...
```
