### ISSUE TITLE
Add testing and docs dependencies to setup.py

### ISSUE THREAD

**Issue by lbeaufort** [pallets/flask-sqlalchemy#725]
While working on a new contributing document for this project (#723), I found that testing and documentation dependencies aren't included in [Flask-SQLAlchemy](https://github.com/pallets/flask-sqlalchemy/blob/master/setup.py)'s setup.py file like they are in [Flask](https://github.com/pallets/flask/blob/master/setup.py#L44-L56)'s.

If you agree that testing and documentation dependencies should be in the `setup.py` file, I can figure out which dependencies Flask-SQLAlchemy needs and add them to the `setup.py` file.

**Comment by rsyring** [comment]
To figure out the dependencies, look at what Tox installs.

**Comment by lbeaufort** [comment]
After talking with @davidism, it makes more sense to keep the docs requirements in the docs requirements.txt file and instruct devs to install the testing requirements directly.

### Docs
```
cd docs
pip install -r requirements.txt
```
### Testing
 `pip install pytest mock tox`

I'll work this in to #723

**Comment by rsyring** [comment]
@davidsm Something to consider: I think it's better to use `setup.py` for the simple reason that it's easy to forget to update docs.  If you put the requirements in `setup.py` and then use that from `tox.ini`, there is never any doubt about what is needed to run tests.  Then, just point this out in the docs and let potential contributors know that is where they should look.  Much less likely docs go out of date that way IMO.

**Comment by davidism** [comment]
Extras are exposed as public metadata, which doesn't really make sense for these. I'll keep thinking about it.

**Comment by rsyring** [comment]
You don't need to elaborate if you don't want to, but I'm not sure what you mean by your last comment.  I semi-frequently see this pattern used in other projects and I've come to appreciate it.  Are we pursuing purity over practicality?  What's the downside to exposing our dependencies as public metadata?
