### ISSUE TITLE
Deprecate configs in version 3?

### ISSUE THREAD

**Issue by lbeaufort** [pallets/flask-sqlalchemy#729]
The [docs indicate](https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/#configuration-keys) that a number of config settings will be deprecated in version 3. Is it too soon to work on removing those settings for version 3?

**Comment by ThiefMaster** [comment]
Since 2.x has its own branch I don't see any reason against removing them in master.

**Comment by davidism** [comment]
Yeah, we can remove these in master.

**Comment by johaven** [comment]
I read _0.8+ or 1.0.10+_ for 2.x, i run with SQLalchemy 1.3.3 and everything seems ok.
Is it an oversight or you have not yet checked 2.4.0 with 1.3.x ?

**Comment by lbeaufort** [comment]
@johaven if I'm understanding your question, Flask-SQLAlchemy is compatible with SQLAlchemy 0.8+ for Python 2.7, 3.4+, and compatible with SQLAlchemy 1.0.10+ w/ Python 3.7.

**Comment by johaven** [comment]
To be more precise, is '1.0.10 and higher' equivalent to '1.x'?

**Comment by lbeaufort** [comment]
I don't believe '1.0.10 and higher' is equivalent to '1.x' in this case. 

It looks like SQLAlchemy does have 1.x versions [starting with 1.0.0](https://docs.sqlalchemy.org/en/13/changelog/changelog_10.html#change-1.0.0), and the [tox](https://github.com/pallets/flask-sqlalchemy/blob/master/tox.ini#L21) file in this project specifies 1.0.10 as the lowest Python 3.7 version, so I think when running Python 3.7, any version of SQLAlchemy below 1.0.10 isn't supported.

**Comment by johaven** [comment]
As I said above, I use the 1.3.x version of sqlalchemy and I want to know if it is compatible (I do not observe any bugs, and the documentation is for me not very clear on the subject ' 1.0.10 and higher 'or maybe it is not up to date)

@lbeaufort  https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-1.0.0

**Comment by kushthedude** [comment]
@lbeaufort Are you on it ?

**Comment by lbeaufort** [comment]
I could be - I was waiting to see what kind of feedback I got from this PR: https://github.com/pallets/flask-sqlalchemy/pull/731

If you wanted to take a shot, feel free to put in a PR! Changes for `3.x` should branch off `master`.

**Comment by davidism** [comment]
These were deprecated in 2.4 and removed in 3.0.
