### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by lbeaufort** [pallets/flask-sqlalchemy#732]
Let's add a code of conduct to be consistent with other Pallets projects. We can copy this one from `Flask`: https://github.com/pallets/flask/pull/3178.

This can be either created with the wizard or with a PR that adds a `CODE_OF_CONDUCT.md` file.

Wizard instructions:
- Go to the [repo community page](https://github.com/pallets/flask-sqlalchemy/community)
- Click on "Add" next to "Code of conduct"

**Comment by kushthedude** [comment]
@lbeaufort I would like to work on it

**Comment by lbeaufort** [comment]
@kushthedude sounds great! If you put in a PR I will review.
