### ISSUE TITLE
Support of Apache Phoenix

### ISSUE THREAD

**Issue by archenroot** [pallets/flask-sqlalchemy#733]
I found some old apache phoenix projects, but not sure if it is or not integrated in flask-sqlalchemy at moment. PHoenix has bit (not much) different dialect (UPSERT instead of INSERT & UPDATE, etc.) which comes from fact its SQL access layer into Hbase.

Any hints welcomed, otherwise I use now phoenixdb module with pure SQL.

**Comment by ThiefMaster** [comment]
I think this is a question for sqlalchemy; flask-sqlalchemy is just a thing wrapper for sqlalchemy, so it's not up to us which databases are supported.

**Comment by archenroot** [comment]
@ThiefMaster - thx for direction, being new in python ecosystem...
