### ISSUE TITLE
Better support for enum

### ISSUE THREAD

**Issue by xim** [pallets/flask-sqlalchemy#735]
I'd like to be able to use an sqlachemy Enum column, and have the name stored to DB while the value is shown in the UI. I've tried the naïve approach:

```
class PageType(enum.Enum):
    html = 'HTML page'
    raw = 'Raw text'

class Page(db.Model):
    [...]
    page_type = Column(db.Enum(PageType, name='page_type'))

class PageAdmin(sqla.ModelView):
    [...]

admin.add_view(PageAdmin(Page, db.session))
```

This works, but shows "Page Type" with the options {html,raw} instead of what I'd like, {HTML page,Raw text}

Doing e.g. `page_type = Column(db.Enum(*[e.value for e in PageType], name='page_type'))` works, but will save the full value in the db instead of the enum name, and looks ugly.

**Comment by davidism** [comment]
This is a behavior of Flask-Admin or SQLAlchemy, not Flask-SQLAlchemy.

**Comment by xim** [comment]
Thanks for clearing it up. Fond the relevant code, and behaviour seems intentional. Was easy enough to work around.

In case anyone else wants this behaviour, I did this:

```
PageAdmin(sqla.ModelView):
    form_choices = {
        'page_type': tuple((c.name, c.value) for c in PageType)
    }
```
