### ISSUE TITLE
create_engine() missing 1 required positional argument: 'engine_opts

### ISSUE THREAD

**Issue by jjRick** [pallets/flask-sqlalchemy#739]
I'm trying to use `db.create_engine` to connect to a second database in a view. My app was working yesterday, but after I tried it on a new machine with a fresh virtualenv, it's no longer working. I think this is due to the changes in #684.

```python
x = 'postgres://*****' 
engine = db.create_engine(x)
```

```pytb
create_engine() missing 1 required positional argument: 'engine_opts'
```

**Comment by davidism** [comment]
`db.create_engine(sa_url, {})`

**Comment by davidism** [comment]
```python
db.create_engine(sa_url, {})
# or, more thoroughly
db.create_engine(sa_url, db.get_options(sa_url, echo=False))
```

I suppose it's not obvious from the docs, but I don't think this method was ever meant to be used the way you're using it. It's there to override how the engine is created, but it's called from within another method, `get_engine`, which is part of the extension's standard behavior.

**Comment by jjRick** [comment]
@davidism   thank you that actually worked db.create_engine(sa_url, {})

what is the method for my situation then ? should i go back to SQLALchemy instead?

**Comment by davidism** [comment]
The method is to make the change that you just tried. Then your code works.

**Comment by jjRick** [comment]
@davidism  yes david it does but i've been chating with lots of ppl on stackoverflow , i think 2 of them with very respected rep. have advised me not to use the library ( flask_sqlALchemy ) and use SQLALchemy instead , that would be the best for my situation but they didnt explain why .

now u said it as well , is there is something i should know about ?? will i be stuck in the future because of this decision ?

**Comment by rsyring** [comment]
If you really want to create an engine on your own, you should use SQLAlchemy directly and don't use db.create_engine().

If you want to have connections to multiple databases, FSA supports that with "binds": https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/
