### ISSUE TITLE
Some master code not included in latest release

### ISSUE THREAD

**Issue by CrystalPea** [pallets/flask-sqlalchemy#751]
Hi there,

This PR was merged in March 2018: https://github.com/pallets/flask-sqlalchemy/pull/613/files

but for some reason it was not released in version 2.4.0

Could you please advise why this is and if it will be included in a release soon?

I'm asking because organisation I work for uses the `count` argument on `paginate()` function included in that PR and we were positive it would be included in the next release since it was merged into master.

I'm looking forward to hearing from you.

**Comment by davidism** [comment]
2.x was branched off of 2.3, that PR was merged into master, which represents some future 2.x or 3.x release. I'll leave it to @rsyring to decide if he wants to cherry pick it to 2.x.

**Comment by CrystalPea** [comment]
Thanks for the info @davidism, fingers crossed then!
