### ISSUE TITLE
Suggestion to update API documentation for SQLAlchemy

### ISSUE THREAD

**Issue by jlorieau** [pallets/flask-sqlalchemy#752]
The API documentation for the SQLAlchemy class provides the following example:
```python
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    db.init_app(app)
    return app
```

https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/

However, it appears that the application context is needed to property configure the database:

```python
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    with app.app_context():
        db.init_app(app)
    return app
```

as per https://stackoverflow.com/questions/46540664/no-application-found-either-work-inside-a-view-function-or-push-an-application

**Comment by davidism** [comment]
You have the app, it's being passed to init_app, nothing in that code block requires an app context.

**Comment by davidism** [comment]
The linked answer was written incorrectly, the context was for creating the tables, not for initializing the extension.

**Comment by jlorieau** [comment]
Thanks for the quick response. I also noted the comment on the app context afterward.
