### ISSUE TITLE
How can I query key's value in a text column from my table?

### ISSUE THREAD

**Issue by SuFIND** [pallets/flask-sqlalchemy#756]
Hi,all.
There is a problem that has bothered me in recent days. I designed an org_score table using the MySql 5.7 database. In the table I designed "range" column of text type, using json string to store time.
The contents of this field are as follows：

`
{“timeStart”:"2017-01-01","timeEnd":"2017-02-01"}
`

I can use the sql of `SELECT * FROM org_score WHERE range->'$.timeStart' >= '2017-01-01';`

This way I can directly query the timeStart key under range.  But I don't know how to use the ORM,  statement of flask-sqlalchemy. Go check this result.

**Comment by ThiefMaster** [comment]
That's a normal alchemy question and not related to flask-sqlalchemy.
