### ISSUE TITLE
Can't find sqlalchemy's exceptions

### ISSUE THREAD

**Issue by flyingdutchman** [pallets/flask-sqlalchemy#764]
I have been trying to import the exception `IntegrityError` to use it in a try/catch bloc.

Since it is always advised to access SQLAlchemy through the flask-sqlalchemy imports, I tried to access the class with `db.exc.IntegrityError`

But then I get the following error:

    AttributeError: 'SQLAlchemy' object has no attribute 'exc'

Is it a normal behavior and I should import from `from sqlalchemy.exc import IntegrityError
` directly or is it a bug ?

**Comment by ThiefMaster** [comment]
> Since it is always advised to access sqlalchemy through the flask-sqlalchemy imports

Who told you that?

**Comment by flyingdutchman** [comment]
> Who told you that?

I read that on some tutorial a while ago.

Good to know, I'll close the issue then since it was my mistake.

Thank you for the quick answer !
