### ISSUE TITLE
how do I get the version?

### ISSUE THREAD

**Issue by invegat** [pallets/flask-sqlalchemy#769]
print(DB)  <SQLAlchemy engine=postgres://cbzzmuglaifvrs:***@ec2-174-129-225-9.compute-1.amazonaws.com:5432/da4fit45q0u0p0

Is there a version number somewhere in there? 

been unable to get a version with a 'tables' parameter  Signature: DB.drop_all(bind='__all__', app=None)

**Comment by davidism** [comment]
```python
import flask_sqlalchemy
flask_sqlalchemy.__version__
```
