### ISSUE TITLE
Weir behavoir on relations

### ISSUE THREAD

**Issue by eamanu** [pallets/flask-sqlalchemy#770]
Hi! I don't know if this is the correct place for this, but I don't found a solucion

I will write this with a example. If I have 2 tables, with a relationship between both:

```
class C(db.Model):
    id = ...
    ....
    fs = db.relationship('F', backref='companies')
  
    ....

class F(db.Model):
    id = ...
    state = db.Column(db.String(255)) # OK or NOK
    c = db.relationship('C', back_populate='fs'
    ....

```
If a make the next query:

```
q = C.query.filter(C.fs.any(state='OK')).all()
```
If I run ```len(q)``` the result is according with my database. But, if I run:
```len(q[0].f)```I have whole F data for  C (q[0]). seems like when I want the
column that represent the relationship, that search whole data on database.

So if I run:

```
for i in q[0].fs:
    print(i.state)
```

I have for example:

```
'OK'
'OK'
'NOK'
'NOK'
 ```
So, the ```q``` result  "does not remember" the ```C.fs.any(state='OK')``` filter

**Comment by ThiefMaster** [comment]
Teis is a sqlalchemy question not related to flask-sqlalchemy.


However, you cannot modify the data a relationship contains like this from the outside. If you do want this, then use this (untested):

`.join(F).filter(F.state == 'OK').options(contains_eager('fs'))`

**Comment by eamanu** [comment]
Thats work correctly! Thanks @ThiefMaster
