### ISSUE TITLE
No documentation for possible workarounds when using multiple binds with identical tablenames

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [pallets/flask-sqlalchemy#773]
Don't know if I'm alone on this one, but it seems to be there's not really a documentation for this one, apart from few haphazard and unsure snippets on some issues.

I personally do not want to move away from flask-sqlalchemy in infras where multiple bindings are needed. Does anyone else feel documenting this would be helpful?

EDIT:

I'm currently using a structure like this to provide different MetaDatas, but I'm not versed enough to take account what implications this solution may have in the long run:

```python
from flask_sqlalchemy.model import Model, DefaultMeta 
from sqlalchemy.ext.declarative import declarative_base
from src.app import DB as db


ReplicaBase = db.make_declarative_base(
    declarative_base(cls=Model, name="Model", metaclass=DefaultMeta))


class AsMaster(db.Model):
    __abstract__ = True
    __bind_key__ = "master"


class AsReplica(ReplicaBase):
    __abstract__ = True
    __bind_key__ = "replica"
```

**Comment by mttbx** [comment]
I have the same problem too, is there a workground?

**Comment by davidism** [comment]
I know this can be confusing, but I'm going to close this in favor of just fixing support for this. #222
