### ISSUE TITLE
No way of importing models without connecting to database

### ISSUE THREAD

**Issue by iamareebjamal** [pallets/flask-sqlalchemy#784]
Currently, there is a huge design problem in Flask SQLAlchemy, that, 

1. It first requires you to eagerly connect to database using the SQLAlchemy constructor, rather than allowing to connect to db using a method at the time we want. But it would be fine even if it did, but 
2. It requires models to be inherited from `db.Model`. I may be ignorant here because I have not read the code of the project, but there must be a good reason for it to require inheriting from an instance, which means it MUST be in a top level module in order to even define the classes.

I cannot even define the model classes before connecting to the database? Not only this is unnecessarily and unintuitively restrictive, it makes debugging and testing next to impossible.

I'm sure maintainers will have a workaround for situations like when I want to *just import* a model and not connect to the database because I want to **unit test** its behavior, where it has nothing to do with the database at all. Where I can use factory boy to create an instance of pure Python Object, I have to wrap it in app context and wait for the DB to get connected. Which means DB setup and tear down is going to get called for each of my test, making a unit test with could run in 10ms take 5 seconds.

Secondly, even if I bite and write all tests as integration tests for my model behaviour, I cannot even import a model in a file, because doing so will require DB connection! This forces me to create strange rules for my utility functions where I have to isolate them from models and enforce no model import policy. What really sucks is that I can't even use python typing to annotate that a method accepts or returns a model without connecting to a database.

I can't be the only one having this problem? Although I've seen that most people in Python community just call DB accessing tests as unit tests as well and move on, but at least in other frameworks like Django, you get a choice of whether you want DB level access or pure python objects.

I like this project, and ignored the inconveniences it caused for a long time and continued to limit my productivity due to its strange and unnecessary constraints and created rules to prevent problems. But now, when I can't even add typing support, I just feel that it is limiting me too much.

It does too much for me and there is no alternative for the project. It is not that trivial that I can write my own wrapper to do the things it does. And it is not feasible for me to fork and maintain it, so I sincerely request the maintainers to look into the problem. 

Maybe I am ignorant and there is a simple solution or workaround to this problem. If so, please let me know. If not, please consider this as a use case, and if no one is willing to work on it, at least consider PRs and point me on what should be done for it.

Thanks

**Comment by davidism** [comment]
You seen to have misunderstood how Flask-SQLAlchemy works. Your title is not true, nor are the two points. In terms of testing, yes you need to use database models with a database (possibly mocked), that's a proprety of SQLAlchemy and other ORMs I'm aware of.

**Comment by iamareebjamal** [comment]
I expected no less from the maintainers. Thank you for confirming my doubts :)
