### ISSUE TITLE
Pagination fencepost error

### ISSUE THREAD

**Issue by evan-csp** [pallets/flask-sqlalchemy#786]
Pagination seems to have an issue where per_page is set to the exact total number of items in the unpaginated response, in some, but not all circumstances.

In this example, staff is defined as a relationship on the School model as such:
`staff = db.relationship(
        'User',
        secondary='grant',
        primaryjoin='School.id==Grant.school_staff_target_id',
        secondaryjoin='Grant.user_id==User.id',
        lazy='dynamic',
        backref='schools_staff'
    )`

I query without pagination like this, and I get the expected number of staff, two:
`staff = School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one()\
        .staff.filter_by(deleted=False).all()`
`Staff: [<User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7>, <User b3769431-b48a-4303-8ec6-b2f0763d21f1>]`

If I paginate setting per_page=2, I correctly get has_next=False, but items only has one result:
`staff = School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one()\
        .staff.filter_by(deleted=False).paginate(1, 2)`
`Staff: [<User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7>]`

If I paginate setting per_page>2, such as 3, items has two results:
`staff = School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one()\
        .staff.filter_by(deleted=False).paginate(1, 3)`
`Staff: [<User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7>, <User b3769431-b48a-4303-8ec6-b2f0763d21f1>]`

This may not actually be a fencepost error. A comprehensive output is below:

Staff ORM query: School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one().staff.filter_by(deleted=False).paginate(1, 2)
Staff: [<User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7>]
Staff pages: 1
Staff has_next False
Staff per_page: 2
Staff total: 1
Staff query: SELECT user.id AS user_id, user.legacy_id AS user_legacy_id, user.email AS user_email, user.first_name AS user_first_name, user.last_name AS user_last_name, user.password AS user_password, user.deleted AS user_deleted 
FROM user, grant 
WHERE ? = grant.school_staff_target_id AND grant.user_id = user.id AND user.deleted = 0

Staff ORM query: School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one().staff.filter_by(deleted=False).paginate(1, 3)
Staff: [<User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7>, <User b3769431-b48a-4303-8ec6-b2f0763d21f1>]
Staff pages: 1
Staff has_next False
Staff per_page: 3
Staff total: 2
Staff query: SELECT user.id AS user_id, user.legacy_id AS user_legacy_id, user.email AS user_email, user.first_name AS user_first_name, user.last_name AS user_last_name, user.password AS user_password, user.deleted AS user_deleted 
FROM user, grant 
WHERE ? = grant.school_staff_target_id AND grant.user_id = user.id AND user.deleted = 0

Staff ORM query: School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one().staff.filter_by(deleted=False).all()
Staff: [User 56fde169-f7bd-4ca1-9e4d-2268a0d71dc7, User b3769431-b48a-4303-8ec6-b2f0763d21f1]

**Comment by evan-csp** [comment]
This appears to be an issue with sqlalchemy.orm.limit() in these circumstances. This query only returns one result:
`staff = School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one()\
        .staff.filter_by(deleted=False).limit(2).all()`

Whereas this query returns both results (expected):
`staff = School.query.filter_by(id='5d2ab3bb1f28426f8148e47543b1cbee').one()\
        .staff.filter_by(deleted=False).limit(3).all()`

**Comment by davidism** [comment]
Sounds like that needs to be reported to SQLAlchemy instead?

**Comment by evan-csp** [comment]
For reference, here is the issue over at SQLAlchemy

https://github.com/sqlalchemy/sqlalchemy/issues/4891
