### ISSUE TITLE
Pass instalation extras to SQLAlchemy

### ISSUE THREAD

**Issue by mvolfik** [pallets/flask-sqlalchemy#796]
### Expected Behavior

When passing extras during installation, Flask-SQLAlchemy should pass them to SQLAlchemy.
So if I  `pip install flask-sqlalchemy[postgresql]`  
or specify `flask-sqlalchemy = {version = "*", extras = ["postgresql"]}` in Pipfile,  
the module `psycopg2` (as specified in [SQLAlchemy setup.py](https://github.com/sqlalchemy/sqlalchemy/blob/926952c4afe0b2e16c4a74f05958bded7b932760/setup.py#L168)) should get installed.

### Actual Behavior

Nothing happens, I have to specify dependency `psycopg2` manually

### Environment (imo irrelevant...)

* Operating system: Docker container, Debian 10 buster
* Python version: 3.7.4
* Flask-SQLAlchemy version: 2.4.1
* SQLAlchemy version: 1.3.11

**Comment by davidism** [comment]
This would require us to mirror every extra that SQLAlchemy has, and keep it in sync forever. There's no significant benefit to this, just add SQLAlchemy and its extras to your requirements.
