### ISSUE TITLE
Adding Replication Master/Slave (FEATURE REQUEST)

### ISSUE THREAD

**Issue by AnderUstarroz** [pallets/flask-sqlalchemy#797]
flask-sqlalchemy is a great library, but it could be even better adding support for replication, a feature quite common on all production environments.
The idea would be adding some options to allow configuration  to allow read and write only on the defined databases, for instance:

```
SQLALCHEMY_DATABASE_URI = 'sqlite:///master.db' # Only Write
SQLALCHEMY_BINDS = {
    'slave': 'sqlite:///slave.db'  # Only Read
}
```

**Comment by davidism** [comment]
I don't plan on adding primary/secondary support to the extension. SQLAlchemy's docs discuss implementations for this which should be possible with the extension as well.
