### ISSUE TITLE
include __all__ in __init__.py file 

### ISSUE THREAD

**Issue by sahasrara62** [pallets/flask-sqlalchemy#798]
### Expected Behavior

this is suggestion for improvement

include `__all__` in the `__init__.py` file , to tell the user all the public method to use, will make it easy to understand and implement, read the code

```python
Paste a minimal example that causes the problem.
```
this is suggestion for  further improvement in the flask-sqlalchemy

### Actual Behavior

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Operating system: ubuntu 18.04
* Python version: 3.7.4
* Flask-SQLAlchemy version: 2.4.1
* SQLAlchemy version: '1.3.10'

**Comment by davidism** [comment]
Thanks for the suggestion. I don't typically like to use all, as it's an extra thing to keep in sync and only really affects import *, which shouldn't be used. Consider things that are documented to be part of the public API.

**Comment by sahasrara62** [comment]
@davidism okay
