### ISSUE TITLE
When only set SQLALCHEMY_BINDS, the pool_size can't be set

### ISSUE THREAD

**Issue by zhongxinghong** [pallets/flask-sqlalchemy#799]
I'm only set `SQLALCHEMY_BINDS` for ALL of my tables, and leave the `SQLALCHEMY_DATABASE_URI` as default `sqlite:///:memory:`. I use MySQL so all uri in BINDS are like `mysql+pymysql://host:post/database`. 

Then I found out I can't set `pool_size` in `SQLALCHEMY_ENGINE_OPTIONS`, or I will get an error:
```
TypeError: Invalid argument(s) 'pool_size' sent to create_engine(), using configuration SQLiteDialect_pysqlite/StaticPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

I check out the source code, in `flask_sqlalchemy.__init__.apply_driver_hacks`, I found that this is because the `SQLALCHEMY_DATABASE_URI` is leave to `None`, then the `sa_uri` from `get_uri` is `sqlite:///:memory:`, then the default `poolclass` will be set to `StaticPool`. This pool only hold one connection so I can't give it `pool_size` parameter. 

So if I want to set the `pool_size` I should also set `poolclass` to `sqlalchemy.pool.QueuePool`.

It used to bother me for a few days. Maybe the documentation should be more detailed. From current docs, I know the default `pool_size` is 5 (but actually the `pool_size` of mysql driver is 10 ...), so I think I can change it by passing the `pool_size` field to `options`. The `SQLALCHEMY_DATABASE_URI` is not required, but the docs don't mention what will happen if i leave it to default. And I don't know the default `poolclass` has been set to `StaticPool`, which is not what I expected.

- Flask-SQLAlchemy: 2.4.0    
- SQLAlchemy: 1.3.8

**Comment by nadwir** [comment]
Hi, 
I have the same problem. 

@zhongxinghong  could you send the code snippet of your solution?

 Thanks!

**Comment by CoburnJoe** [comment]
Have you tried setting ``sqlite:///:memory:`` as a connection in ``SQLALCHEMY_BINDS``, then selecting that bind?
What's the purpose of this in-memory database - you mention the pool_size of  MySQL, so is this SQLite DB for unit tests...?

**Comment by yaooort** [comment]
I use mysql how to solve this problem, thank you!

**Comment by zhongxinghong** [comment]
> Have you tried setting `sqlite:///:memory:` as a connection in `SQLALCHEMY_BINDS`, then selecting that bind?
> What's the purpose of this in-memory database - you mention the pool_size of MySQL, so is this SQLite DB for unit tests...?

This in-memory db is just the default value of `SQLALCHEMY_DATABASE_URI`. I only use MySQL in my project.

**Comment by zhongxinghong** [comment]
> I use mysql how to solve this problem, thank you!

As I mentioned above, In this case, you need to set `poolclass` in `SQLALCHEMY_ENGINE_OPTIONS` at the same time if you want to change the `pool_size`, because the default `poolclass` was set to `StaticPool` by the default value of `SQLALCHEMY_DATABASE_URI`, which doesn't support changing pool size.

**Comment by CoburnJoe** [comment]
I think there's several things going on here.

By default, SQLite doesn't support connection pooling (it can be enabled) -- this would explain your ``TypeError``. 

The Flask-SQLAlchemy docs indicate that version 3 has removed this default of ``sqlite:///memory:``` (https://github.com/pallets/flask-sqlalchemy/blob/db02fd4c821b8aa8c6e47391fce6f064def6a363/docs/config.rst), so this may help you out once released.

But if you're using ``SQLALCHEMY_BINDS``, in theory it shouldn't matter that the default URI is SQLite, as you'd never use it (choosing instead to use one of your binds...). How are you choosing tenant/switching DBs with binds? (https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/#binds)

**Comment by yaooort** [comment]
## As you said, do I need to set this up?


```python
SQLALCHEMY_ENGINE_OPTIONS = {
    'pool': QueuePool(creator),
    'pool_size' : 10,
    'pool_recycle':120,
    'pool_pre_ping': True
}
```

**Comment by CoburnJoe** [comment]
I'd like to know how you are choosing your databases. Are you choosing binds per table/DB:
`__bind_key__ = 'users'` or `db.create_all(bind='appmeta')`

Or are you using custom tooling to choose tenants?

It doesn't really matter how you choose a bind, but you do need to do it if you're not.

The flask-sqlalchemy docs are quite comprehensive on this topic: https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/#binds

Note the following line:

> If no bind key is specified for a model the default connection is used instead (as configured by SQLALCHEMY_DATABASE_URI).

**Comment by yaooort** [comment]
### My custom selection

```python
class AutoRouteSession(SignallingSession):
    # 选择的数据库
    bind_key = None

    def get_bind(self, mapper=None, clause=None):
        """获取会话使用的数据库连接engine"""
        try:
            state = get_state(self.app)
        except (AssertionError, AttributeError, TypeError) as err:
            raise RuntimeError('state 获取会话出错' + str(err))
        if self.bind_key:
            # 指定
            # print('Using DB bind: _name={}'.format(self.bind_key))
            return self.clear_old_conn(state)
        else:
            if self._flushing:
                # 增删改操作, 使用主库
                self.set_to_write()
            else:
                # 读操作使用从库
                self.set_to_read()
            if self.bind_key:
                # 指定
                # print('Using AUTO DB bind: _name={}'.format(self.bind_key))
                return self.clear_old_conn(state)
            # 默认数据库
            # print('Using default DB bind: _name={}'.format(db.default_key))
            return state.db.get_engine(self.app, bind=db.default_key)

    def clear_old_conn(self, state):
        rv = state.db.get_engine(self.app, bind=self.bind_key)
        self.bind_key = None
        return rv

    def set_to_write(self):
        """使用写数据库"""
        # print('使用写数据库')
        if db.master_keys:
            self.bind_key = choice(db.master_keys)
            # print('使用写数据库' + self.bind_key)

    def set_to_read(self):
        """使用读数据库"""
        # print('使用读数据库')
        if db.slave_keys:
            self.bind_key = choice(db.slave_keys)
            # print('使用读数据库' + self.bind_key)

```

**Comment by CoburnJoe** [comment]
That itself looks ok -- although it does depend how you use it.
Your project does not have a bind key set when it runs at some stage, and raises this error. As mentioned above, that SQLite connection is ONLY run when you don't specify a bind, so I think the problem is somewhere in your implementation.

**Comment by zhongxinghong** [comment]
> I'd like to know how you are choosing your databases. Are you choosing binds per table/DB:
> `__bind_key__ = 'users'` or `db.create_all(bind='appmeta')`
> 
> Or are you using custom tooling to choose tenants?
> 
> It doesn't really matter how you choose a bind, but you do need to do it if you're not.
> 
> The flask-sqlalchemy docs are quite comprehensive on this topic: https://flask-sqlalchemy.palletsprojects.com/en/2.x/binds/#binds
> 
> Note the following line:
> 
> > If no bind key is specified for a model the default connection is used instead (as configured by SQLALCHEMY_DATABASE_URI).

You are right! I explicitly set `__bind_key__` for ALL of my tables, and I use `db.create_all()` to create tables all at once, In fact, `SQLALCHEMY_DATABASE_URI` is useless in my project.

I have a clone of the `main db` which is running for normal business in production env, and I have a `error db` for tracing errors. I'm running the production and development env on the same server. I use the clone one of main db in my development env, but I use the same error db on both production and development env. I have `main` key and `error` key for `__bind_key__`, tables bound to `main` key will have different url on different env, and tables bound to `error` key will have the same url on different env. I must ensure that all of my tables are bound to the right database, so I explicitly set `__bind_key__` for ALL of my tables.

**Comment by zhongxinghong** [comment]
I've found the same issue #663, and this problem has been solved in https://github.com/pallets/flask-sqlalchemy/pull/731 . Emm ...  maybe my issue is redundant and I need to close it :) I didn't notice that this problem has been raised. I feel sorry for that ...

> But if you're using `SQLALCHEMY_BINDS`, in theory it shouldn't matter that the default URI is SQLite, as you'd never use it (choosing instead to use one of your binds...).

If you want to know the reason, you can read the source code of `flask_sqlalchemy/__init__.py` in 2.4.0

**Comment by zhongxinghong** [comment]
> ## As you said, do I need to set this up?
> ```python
> SQLALCHEMY_ENGINE_OPTIONS = {
>     'pool': QueuePool(creator),
>     'pool_size' : 10,
>     'pool_recycle':120,
>     'pool_pre_ping': True
> }
> ```

According to the source code of `sqlalchemy`, you should set it as this:
```python
SQLALCHEMY_ENGINE_OPTIONS = {
    "poolclass": QueuePool,
    "pool_size": 10,
}
```
