### ISSUE TITLE
Exceptions during DB Server reboot - no reconnect

### ISSUE THREAD

**Issue by caliph007** [pallets/flask-sqlalchemy#802]
I have a standard setup of flask_sqlalchemy and an AWS RDS with postgresql.

I initialize the DB adapter the standard way:

```
from flask_sqlalchemy import SQLAlchemy
from flask import Flask

app = Flask(__name__)
db = SQLAlchemy()

db.init_app(app)

class Example(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(256))
```

If I reboot the RDS server and a SELECT starts during reboot I get:

> psycopg2.OperationalError: terminating connection due to administrator command SSL connection has been closed unexpectedly
> 
> The above exception was the direct cause of the following exception:
> 
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command SSL connection has been closed unexpectedly

That I understand. The DB is unavailable.

BUT: After that the application cannot recover from the situation because:

> sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
> 
> The above exception was the direct cause of the following exception: sqlalchemy.exc.StatementError:
> 
> (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back

I understand the application throws exceptions during reboot.

But what puzzles me that it never recovers.

There is no write transaction to the DB! I don't understand what rollback the exception is describing.

**Comment by ThiefMaster** [comment]
Are you in debug mode? AFAIK you need to do an explicit rollback after any error while in debug mode (so you still have all the data around in a debugger that'd be lost when rolling back).

**Comment by caliph007** [comment]
Thanks for your answer. Quick questions:
a) Do you mean flask debug mode? : e.g. environment variable FLASK_DEBUG=1 
I cannot find a flask_alchemy debug mode in the docs.

b) what rollback can be done on a SELECT ? Do you refer to : session.rollback() ?

**Comment by caliph007** [comment]
After investigation my best guess is to avoid such a situation, where I need a rollback or the application cannot reconnect, I have to wrap each SELECT

e.g.
`Model.query.filter(...).all()`

into a try/except block?

```
try:
  Model.query.filter(...).all()
except:
  db.session.rollback()

```
Is that the intended way to create resilience against a DB server reboot?

**Comment by davidism** [comment]
This appears to be a general issue with database connections and SQLAlchemy, it's not clear that Flask-SQLAlchemy has any control over this.
