### ISSUE TITLE
How to set autoincrement value from 10000

### ISSUE THREAD

**Issue by shivgana** [pallets/flask-sqlalchemy#844]
as default database is sqlite3.
i want to set autoincrement value to 10000. So started browsing for solution, but no solution worked.

**Comment by ThiefMaster** [comment]
This has nothing to do with flask-sqlalchemy.

**Comment by shivgana** [comment]
but we create database with sqlalchemy, so

**Comment by ThiefMaster** [comment]
Flask-SQLAlchemy is just a thing wrapper for SQLAlchemy. So this is a SQLAlchemy question in the end. :)

PS: Better start with a real DB like Postgres. Setting a start value for a serial column there is quite easy.
