### ISSUE TITLE
.paginate() seems to override .options(load_only('col_1', 'col_2')) and include all columns

### ISSUE THREAD

**Issue by christopherpickering** [pallets/flask-sqlalchemy#851]
### Expected Behavior

Hi, I'm trying to use paginated results of a query and only selected a handful of columns in the table, however, it seems to always return all columns in the table, not just what I specify. 

```python
stuff = Table.query.filter_by(col_1='this')).options(load_only('col_1', 'col_2')).paginate(1, 10, False)
```
stuff.items this should return data with only two columns, col 1 and 2.

### Actual Behavior

stuff.items is returning all columns in the table.

### Environment

* Python version: 3.8.2
* Flask-SQLAlchemy version:2.4.3
* SQLAlchemy version:1.3.17

**Comment by davidism** [comment]
Does this happen if you use `limit` and `offset` directly?

**Comment by christopherpickering** [comment]
Thanks,
so if I put just .limit(5) in place of .paginate, I get the sql query that is limited to the one column. When I add .all() to get the results then I get all columns. With offset it is the same result - nice sql query until I add ".all()" to get the results.

**Comment by davidism** [comment]
Then it's an issue with SQLAlchemy. All Flask-SQLAlchemy's `paginate` does is call those methods. Please report it to them.

**Comment by christopherpickering** [comment]
@davidism it sounds like sqlAlchemy's prefered method for selecting just a few columns is this -
https://github.com/sqlalchemy/sqlalchemy/issues/5457#issuecomment-657918400

```python
session.query(Thing.col1, Thing.col2)
```

however, the way we query with flask-sqlalchemy is 
```python
Table.query. ...
```
and has no place for column names inside of query.

Is there a syntax I should be using instead of this? Thanks!

**Comment by christopherpickering** [comment]
ah, I found it I think, thanks for documenting the source code, it aways comes in handy one day  :)

instead of 
```python
Table.query...
```

use

```python
db.session.query(Table.col1)...
```

and it works perfectly. 

I created a pull request to add to the docs -https://github.com/pallets/flask-sqlalchemy/pull/853

Thanks!
