### ISSUE TITLE
Connecting to database at startup to prevent first request delay

### ISSUE THREAD

**Issue by mvolfik** [pallets/flask-sqlalchemy#879]
I would like to configure Flask-SQLA to connect to my database as soon as I call `db.init_app(app)`, because doing this on the first request causes a significant delay. How do I do this? Docs or Google don't provide any help on this

**Comment by ThiefMaster** [comment]
You don't want that :) You usually also don't want just one connection. SQLAlchemy maintains a connection pool so if your first request has a significant delay I don't think it's related to this.

**Comment by mvolfik** [comment]
Hmm, I guess I'll have to read up on this.

Until now I thought it works like this:
- due to Python being single threaded, one instance of app can only handle one request at a time
- one instance of app won't need more than 1 db connection, as it can't do multiple db operations at once
- when gunicorn runs multiple app instances (workers), they are completely separate with their own sqlalchemies and pools

Which part of this do I understand wrong?

**Comment by mvolfik** [comment]
And I can definitely confirm increased response time of first request that connects to database, no matter if I previously (between app startup and database-reading request) send some requests without database access.
