### ISSUE TITLE
Exception when setting sa_url.query default due to immutable type

### ISSUE THREAD

**Issue by failys** [pallets/flask-sqlalchemy#884]
### Expected Behavior

The below should be successful
```python
sa_url.query.setdefault("charset", "utf8")
```

### Actual Behavior

The following exception is thrown:  AttributeError: 'sqlalchemy.cimmutabledict.immutabledict' object has no attribute 'setdefault'

You can see the full traceback on Travis here: https://travis-ci.org/github/cairis-platform/cairis/builds/741329319

This is only an issue with SQLAlchemy 1.4.0b1.  
### Environment

* Python version: 3.8
* Flask-SQLAlchemy version: 2.4.4
* SQLAlchemy version: 1.4.0b1

**Comment by davidism** [comment]
That's SQLAlchemy, Flask-SQLAlchemy has no effect on that. I believe making the url object immutable was a deliberate change.

**Comment by failys** [comment]
If SQLAlchemy has made the decision to make that object immutable, why is Flask-SQLAlchemy treating it like it isn't?
