### ISSUE TITLE
Allow db.create_all() to accept the actual bind parameter

### ISSUE THREAD

**Issue by talhajunaidd** [pallets/flask-sqlalchemy#904]
For `db.create_all()` we have to specify the key what now has to be hardcoded or read from `app.extensions['sqlalchemy']` 
and there is no way to get information from Engine/session what bind-key it belongs to.
Can we allow that `bind` parameter for  `db.create_all()`   to accept the actual bind?

for example
```python
db.create_all(bind=db.session.bind)
```

**Comment by davidism** [comment]
`create_all` already accepts a `bind` parameter, it should be the string `"__all__"` (default), a string corresponding to one of the binds defined in `SQLALCHEMY_BINDS`, or a list of such strings.
