### ISSUE TITLE
Copy previous ident_func code from Werkzeug

### ISSUE THREAD

**Issue by davidism** [pallets/flask-sqlalchemy#915]
Werkzeug 2.0 is changing how `Local` is implemented to use a `ContextVar` instead. This means that the `ident_func` is no longer relevant (and probably shouldn't have been used externally before either). Currently, it raises a `RuntimeError`, but soon it will show a `DeprecationWarning`. Either way, Flask-SQLAlchemy shouldn't try to use Werkzeug's implementation anymore.

Since Flask-SQLAlchemy doesn't have a notion of coroutine-local connections anyway, we can copy Werkzeug's `ident_func` import block and use it locally instead. https://github.com/pallets/werkzeug/blob/44866cc6419dd1742b86a0b7bccd32ba2eb58f77/src/werkzeug/local.py#L11-L17

Environment:

- Python version: >=3.7
- Flask-SQLAlchemy version: latest
- SQLAlchemy version: 2.0.0b1

**Comment by adgnabro** [comment]
Hi ! I can help on this one if you want ?

**Comment by DCyph** [comment]
Hi, how can this issue be overcome in the meantime?

**Comment by davidism** [comment]
It doesn't need to be, Werkzeug 2.0 isn't released yet.

**Comment by klunkean** [comment]
Maybe this helps anyone:
I allowed prereleases in my Pipfile (for black) so I had Werkzeug 2 automatically installed which made my code not runnable.
I wrote `werkzeug="<2.0.0"` in my Pipfile to make it work again.
