### ISSUE TITLE
Sqlite db.create_all() crash with AttributeError: can't set attribute

### ISSUE THREAD

**Issue by JonSilverman** [pallets/flask-sqlalchemy#938]
Environment:

- Python version: 3.9.2
- Flask-SQLAlchemy version: 2.4.4
- SQLAlchemy version: 1.4.0

**Comment by ThiefMaster** [comment]
You need to use flask-sqlalchemy 2.5.1 for sqlalchemy 1.4

**Comment by davidism** [comment]
Duplicate of #885, #910, and other duplicates.
