### ISSUE TITLE
The README "changes" link is not valid

### ISSUE THREAD

**Issue by Manawasp** [pallets/flask-sqlalchemy#940]
Hello,

There is just a small typo in a link from the README or a failure in the redirection:

`- Changes: https://flask-sqlalchemy.palletsprojects.com/changes/`

The URL doesn't match any existing URL I found the right one from the home page in the additional detail:

`https://flask-sqlalchemy.palletsprojects.com/en/2.x/changelog/`

**Comment by davidism** [comment]
You're looking at the master branch, so you need to look at the master docs. It will be in sync once 3.0 is released.
