### ISSUE TITLE
SQLAlchemy.get_app() should prefer using self.app instead of Flask.current_app

### ISSUE THREAD

**Issue by AbdealiJK** [pallets/flask-sqlalchemy#972]
I have a scenario where we are writing multiple flask applications which are being hosted together with a `DispatcherMiddleware`.
The issue I am facing is that if I use a common model between both applications - I get the error:
```python
  File "/home/abdealijk/app/app.py", line 29, in second
    item = MyModel.query.first()
  File "/home/abdealijk/app/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/abdealijk/app/venv/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/abdealijk/app/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1022, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/abdealijk/app/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3308, in __call__
    return self.class_(**local_kw)
  File "/home/abdealijk/app/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 175, in __init__
    track_modifications = app.config['SQLALCHEMY_TRACK_MODIFICATIONS']
KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
```

I went through the code in this library and found that this is most likely the culprit:
https://github.com/pallets/flask-sqlalchemy/blob/2.5.1/flask_sqlalchemy/__init__.py#L1036
Here, I see that the priority order in `SQLAlchemy.get_app()` is:
1. reference_app provided in args
2. The Flask.current_app
3. The self.app provided during initialization
This seemed odd - because I assume that if I provide an explicit app - it should have used that instead of trying to get it from Flask.
I tried changing this order to prefer using `self.app` instead of `Flask.current_app` - and things worked fine!

Here is a minimal example:
```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer
from werkzeug.middleware.dispatcher import DispatcherMiddleware

app1 = Flask('app1')
app1.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///:memory:'
app1.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app1)


class MyModel(db.Model):
    id = Column(Integer, primary_key=True, autoincrement=True)


app2 = Flask('app2')


@app1.route('/first')
def first():
    item = MyModel.query.first()
    item_id = item.id if item else None
    print('Got item=', item_id)
    return {'item': item_id}


@app2.route('/second')
def second():
    item = MyModel.query.first()
    item_id = item.id if item else None
    print('Got item=', item_id)
    return {'item': item_id}


if __name__ == '__main__':
    app1.wsgi_app = DispatcherMiddleware(app1.wsgi_app, {'/app2': app2.wsgi_app})
    app1.run(port=9999)
```
Now try calling:
```bash
$ curl --request GET http://127.0.0.1:9999/app2/second --header 'Content-Type: application/json'
```

Environment:
- Python version: 3.9.1
- Flask version: 2.0.0
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.3.23

**Comment by davidism** [comment]
Current behavior is intentional and correct. See numerous existing questions about this in the issue tracker.

**Comment by AbdealiJK** [comment]
Got it, thanks.

Just noting the comment which seemed to clear it up for me here in case others coming looking for an answer:
https://github.com/pallets/flask-sqlalchemy/issues/607#issuecomment-372878485
> self.app is a convenience for small applications, do not rely on it. Push an application context when you need an application context.
