### ISSUE TITLE
Support for context manager style

### ISSUE THREAD

**Issue by lverweijen** [pallets/flask-sqlalchemy#973]
In sql-alchemy there are two styles of working with sessions:

- Context manager
- Commit as you go

See https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#managing-transactions

I would like to use the "context manager"-style with flask-sqlalchemy but it doesn't seem to be supported.

Running:
```
with db.session.begin():
    db.session.add(some_object())
    db.session.add(some_other_object())
```

Gives:

```
sqlalchemy.exc.InvalidRequestError: a transaction is already begun on this session
```

**Comment by davidism** [comment]
Sounds like you want [`begin_nested`](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.begin_nested).
