### ISSUE TITLE
Using dataclass with declarative

### ISSUE THREAD

**Issue by jonathanberthias** [pallets/flask-sqlalchemy#992]
The SQL-Alchemy docs [show an example](https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#example-two-dataclasses-with-declarative-table) to map a dataclass to a table using:

```Python
from dataclasses import dataclass
from dataclasses import field

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy.orm import registry

mapper_registry = registry()

@mapper_registry.mapped
@dataclass
class User:
    __tablename__ = "user"

    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
```

I tried to achieve the same thing using Flask-SQLAlchemy:
```Python
from dataclasses import dataclass
from dataclasses import field

from sqlalchemy import Column
from sqlalchemy import Integer

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

@dataclass
class User(db.Model):
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
```
which yields the following error: `sqlalchemy.exc.ArgumentError: Mapper mapped class User->user could not assemble any primary key columns for mapped table 'user'`

I also tried to use the `mapper_registry` with
```Python
@db.Model.registry.mapped
@dataclass
class User:
    __tablename__ = 'user'
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
```
but I then lose all the benefits from Flask-SQLAlchemy.

Would it be possible to add support for dataclasses in Flask-SQLAlchemy?

**Comment by davidism** [comment]
Flask-SQLAlchemy doesn't do anything in particular to the base model that should affect this, so there's not really anything to "support", it should already just work. If you want to submit a PR that fixes whatever is causing this, happy to review it.
