### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by kasium** [pallets/flask-sqlalchemy#999]
Hello all,
did you already consider to add type hints to your code? SQLAlchemy does this with https://github.com/sqlalchemy/sqlalchemy2-stubs.

Thanks,
Kai

**Comment by davidism** [comment]
The vast majority of Flask-SQLAlchemy is a proxy to SQLAlchemy. Other than that, there's not much. I've added type annotations to the other Pallets projects, but I'm not sure how useful it would be here. If we do add them, I will work on it, it's not really something general contributors can add (in a way that I'm satisfied with), so I'll close this for now.

**Comment by kasium** [comment]
@davidism thanks for your comment. You are right, most of the things are proxies. However, it would be great to have types for the `SQLAlchemy` object. This might be trivial, but I try to reach no type ignores in my projects and FlaskSQLAlchemy is one of the missing pieces.

If you could consider this in the future, it would be great
